### ISSUE TITLE
Deploy 에러

### ISSUE THREAD

**Issue by dkfma4915** [JEoN-Ha/Senior-Project#103]
![image](https://user-images.githubusercontent.com/52308823/113887116-2f891d80-97fc-11eb-953a-60c76433c37f.png)

`Unhandled Rejection (TypeError): Cannot read property '0' of undefined`라는 에러가 계속 발생..

우리가 원인이라고 생각했던 Menu.js의 `credentials: 'include'`을 없앴을때도 메뉴는 제대로 뜨고,
Basket.js에서 계속 에러가 나는데 이유를 못찾았어 ㅠㅠ

일단 나는 원래 하던 라우터 디버깅 작업을 계속하고, 지연이가 이 오류의 원인을 알아봐 줄 수 있을까??
`credentials: 'include'`가 없을 때도 메뉴 데이터는 제대로 뜨는 걸 보니 다른 원인인 것 같아.. !!

**Comment by kiJiyeon** [comment]
에쓰!!! 알아볼게!!!!

**Comment by kiJiyeon** [comment]
엇 일단 api명세서에 getBasket이 없당,,,,

**Comment by dkfma4915** [comment]
> 엇 일단 api명세서에 getBasket이 없당,,,,

히엑 ...!!!!! 아 내가 장바구니 내역 불러오는거 없다고해서 나중에 추가해서 그런가??

**Comment by kiJiyeon** [comment]
> > 엇 일단 api명세서에 getBasket이 없당,,,,
> 
> 히엑 ...!!!!! 아 내가 장바구니 내역 불러오는거 없다고해서 나중에 추가해서 그런가??

아 그런가?? 그럼 일단 api에 빠진 것들 추가해서 다시 올려볼게!!!

**Comment by dkfma4915** [comment]
> > > 엇 일단 api명세서에 getBasket이 없당,,,,
> > 
> > 
> > 히엑 ...!!!!! 아 내가 장바구니 내역 불러오는거 없다고해서 나중에 추가해서 그런가??
> 
> 아 그런가?? 그럼 일단 api에 빠진 것들 추가해서 다시 올려볼게!!!

오케잉!!
