### ISSUE TITLE
멘토님께 랍스터작전 제안

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#104]
멘토님! 저희끼리 미팅 관련해서 얘기를 해봤는데, 코로나 확진자가 너무 많이나와서 한동안은 오프라인으로 만나기 쉽지않을 것 같다고 결론을 내렸습니다! 
그래서 온라인으로 미팅을 몇번 진행하고 몇달 뒤에 저번에 말씀하셨던 랍스터 먹으러 가는건 어떠신가요?!

**Comment by jongfeel** [comment]
오 아주 좋습니다.

바이킹스 워프 롯데월드로 가면 좋겠군요 ㅋㅋㅋ
http://www.ivikings.co.kr/akg/ko/storetype/wharf.asp

일단 먹고 미팅 하는 것도 방법이니까요 (선먹후미팅)
자유롭게 작전을 짜보시면 좋을 것 같습니다.

**Comment by dkfma4915** [comment]
> 오 아주 좋습니다.
> 
> 바이킹스 워프 롯데월드로 가면 좋겠군요 ㅋㅋㅋ
> http://www.ivikings.co.kr/akg/ko/storetype/wharf.asp
> 
> 일단 먹고 미팅 하는 것도 방법이니까요 (선먹후미팅)
> 자유롭게 작전을 짜보시면 좋을 것 같습니다.

오 좋습니다!!! 완전 맛있어보여요 ㅜㅜ

**Comment by jongfeel** [comment]
그러면 중간고사도 끝났으니 슬슬 온라인으로 미팅을 진행해 볼까요?

**Comment by kiJiyeon** [comment]
> 그러면 중간고사도 끝났으니 슬슬 온라인으로 미팅을 진행해 볼까요?

넵!! 혹시 다음주에 미팅 불가능하신 날 있으신가요?!

**Comment by jongfeel** [comment]
5월 20일 목요일만 아니면 될 것 같습니다.

**Comment by kiJiyeon** [comment]
그럼 5월 21일 금요일 11시에 미팅 진행하는거 괜찮으신가요??

**Comment by jongfeel** [comment]
네, 금요일 괜찮습니다.
랍스터 할당량 채우려면 부지런히 7번 회의 다 채워야 하니까 시간날때마다 진행하면 좋을 것 같습니다.
