### ISSUE TITLE
9th online meetings, 2021-05-27

### ISSUE THREAD

**Issue by jongfeel** [JEoN-Ha/Senior-Project#105]
## 하드웨어 세팅 후 시연

- 다시 찍을 거면 주문 화면 모바일 세로 화면으로 맞춰서 찍고 => 데스크톱 웹, 모바일 웹 화면 동시에 보여주기
- OCR 화면 캡쳐한거 추가하기
- (옵션) 만약 할 수 있으면 하얀 박스 대신 음식 플라스틱 장난감으로 대체하기

## 6월에 저녁 약속 잡기

- 기말고사 끝나고 6월 14일 월요일 부터 6월 24일 목요일 사이
- 날짜 알려주세요.

**Comment by jongfeel** [comment]
제가 안되는 날짜가 정확하게 있어서 한번 정리해 봤습니다.
여러분들도 안되는 날짜 있으면 아래 리스트에서 취소 표시선 해주시면 될 거 같아요.

그리고 잠실 바이킹스 워프가 월~목 하고 금요일 하고 시간대가 달라서 확인하고 가야할 것 같습니다.

평일 18:00 - 21:00Dinner(월~목)
금요일 17:00 - 18:50Dinner 1부(금)
금요일 19:10 - 21:00Dinner 2부(금)

그리고 2주 전에 예약하는 것도 어려울 수 있다고 하니 날짜를 미리 정하는 게 좋을 것 같아요.

- 14일 월
- ~15일 화~
  - jongfeel: 에버랜드 가족여행
- 16일 수
- 17일 목
- 19일 금
- 21일 월
- 22일 화
- 23일 수
- 24일 목
- ~25일 금~
  - jongfeel: 1st academic conference 참석

**Comment by dkfma4915** [comment]
안그래도 저희끼리 얘기해봤었는데 16일 수요일 어떠신가요??!

**Comment by jongfeel** [comment]
좋습니다!

6시에 잠실 오실 수 있는거죠?

**Comment by fora22** [comment]
네네!! 16일 수요일 오후 6시 잠실역에서 보면 될까요?

**Comment by jongfeel** [comment]
네 입장해야 하는 시간이 6시니까
잠실역이 아니라 잠심 바이킹스워프 앞 6시겠죠 ㅋㅋ

**Comment by dkfma4915** [comment]
ㅋㅋㅋㅋㅋ네! 16일 바이킹스워프 앞에서 봬요!

**Comment by jongfeel** [comment]
제가 잠실점 연락해 보니까 이번달은 예약이 다 차서 못간다고 하네요 ㄷㄷㄷ

그래서 코엑스몰점으로 예약했는데 여기는 괜찮을까요?

**Comment by fora22** [comment]
전 괜찮습니다! ㅎㅎ

**Comment by dkfma4915** [comment]
저도 괜찮습니다!!ㅎㅎㅎ

**Comment by jongfeel** [comment]
오늘입니다. 바이킹스워프 코엑스점 오후 6시에요!

**Comment by dkfma4915** [comment]
네!!!ㅎㅎㅎㅎ

**Comment by kiJiyeon** [comment]
넵!!! ㅎㅎㅎㅎ

**Comment by fora22** [comment]
넵! ㅎㅎ
