### ISSUE TITLE
Next meeting schedule

### ISSUE THREAD

**Issue by jongfeel** [JEoN-Ha/Senior-Project#106]
사실상 완료한 거나 다름 없긴 한데
지난 주 까지 세번 진행했고
앞으로 네 번 더 회의가 진행되어야 합니다.

그래서
7월
8월
9월
10월

이렇게 월별로 한번씩 해서 네번 미팅이 진행되면 좋을 것 같고
근황 토크 정도 하면 좋을 것 같은데 어떠신가요?

**Comment by kiJiyeon** [comment]
넵!! 좋습니다

**Comment by dkfma4915** [comment]
네! 좋아요 ㅎㅎㅎ

**Comment by fora22** [comment]
넵 좋습니다 ㅎㅎㅎ

**Comment by kiJiyeon** [comment]
@jongfeel 멘토님 7월 온라인 미팅 21일 수요일에 가능하신가요?!

**Comment by kiJiyeon** [comment]
넵!! 알겠습니다~!! 시간은 11시 어떠세요~?

**Comment by jongfeel** [comment]
좋습니다
