### ISSUE TITLE
Typescript 사용에 관하여

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#14]
11일 금요일 저희 오프라인 미팅을 했는데요(노션에 정리했습니다).

React, Vue 중에서 React로 진행하기로 의견이 기울었습니다. 

다만 제가 이전에 들었던 얘기로는 TypeScript를 쓰면 좋다고 들어서요(사실 TypeScirpt를 써보고 싶은 마음도 있습니다(팽 의견)).

[제안 근거 1](https://www.notion.so/fora22/2020-12-12-7439b535406e4a99906c02877845627e#e77db060464f44a893253bc833b32bce)  [제안 근거 2](https://www.notion.so/fora22/2020-12-12-7439b535406e4a99906c02877845627e#3400ae7fa6a34a0e8426f347feacdb8c)

멘토님의 생각을 듣고 싶습니다! ㅎㅎ @jongfeel

**Comment by jongfeel** [comment]
Type script 해보면 좋긴 합니다.

이것도 하나 알려드리면 type script가 왜 필요했는지를 얘기할 수 있으면 좋습니다.

**Comment by fora22** [comment]
어.. 다른 사람에게 우리가 왜 TypeScript를 사용하고 필요했는지 얘기할 수 있으면 좋다는 뜻인가용??

**Comment by jongfeel** [comment]
네 다른 사람에게 설명할 수 있으면 좋고요.

무엇보다도 우리가 왜 type script를 쓰게 되었는지에 대한 설명이 잘 되면 좋다는 거죠.

**Comment by fora22** [comment]
TypeScript를 사용해보고 비교를 한 번 해봐야겠네요. 감사합니다! ㅎㅎ
