### ISSUE TITLE
Github main branch에 있는 폴더 삭제로 인해 

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#15]
제가 작업공간을 main branch에 잘못 만들어서 삭제하고 Push했다가 나머지 README를 포함해서 만들어 놓은 폴더가 다 삭제되었습니다...

 main branch에 삭제된 기록이 있으면 나중에 merge할 때, 다 지워져버린다고 들었는데 혹시 해결방법이 있을까요??

**Comment by fora22** [comment]
git log를 reset 하고 `git --force origin main` 으로  강제로 Push 하면 git 변경내역을 Local하고 Remote 둘 다 변경될 수 있을듯?!

**Comment by kiJiyeon** [comment]
> git log를 reset 하고 `git --force origin main` 으로 강제로 Push 하면 git 변경내역을 Local하고 Remote 둘 다 변경될 수 있을듯?!

오 그런가요?! 제발,,,,

**Comment by jongfeel** [comment]
음 어떤 상황인지 정확히 이해가 되지는 않는데

이후에 피드백 상태를 보고 판단해봐야 할 거 같습니다.

**Comment by kiJiyeon** [comment]
> 음 어떤 상황인지 정확히 이해가 되지는 않는데
> 
> 이후에 피드백 상태를 보고 판단해봐야 할 거 같습니다.

넵! 알겠습니다 ㅎㅎ

**Comment by fora22** [comment]
README 파일이 삭제되서 Conflict가 뜨는데 다행히 1개라서 Conflict만 잘 조정해주면 될듯!
Reset까지는 필요 없을 것 같아! @kiJiyeon

**Comment by fora22** [comment]
@kiJiyeon Issue 해결되면 close 해주세요~
