### ISSUE TITLE
Review Meeting에 관하여 제안

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#16]
# 기존 Review Meeting Rule
- 다음 회의 날짜를 정해놓는다.
- 회의 때 논의할 사항이 없으면 실제 회의는 없어지고 다음 회의 날짜를 잡는다.
# 제가 생각한 문제점
- 회의 하자니 시간 맞춰 회의하기에는 주제가 간단하고
- Issue 올리자니 '굳이..?' 라는 생각이 든다.
- 그리고 이런 게 생각보다 많다.
# 그러므로 제안(Suggest)
- 회의가 끝나면 다음 Review Meeting Issue 를 올린다.
- 회의(의견을 묻거나, ~해줬으면 or ~했으면 좋겠다 싶은 거, 진행에 있는 결정 사항 의논 등) 내용이 생길 때마다 Issue에 올려서 대화한다.
  - 이 때 각 주제별로 새로 Issue를 올리고 Review Meeting Issue에 링크를 남긴다.
  - #을 쓰면 알아서 Issue와 PR에 대한 링크를 고를 수 있다.
- 회의 날짜까지 모든 Issue에 대하여 결론이 지어지면 해당 날짜의 회의는 없어진다.
- 만약 결론이 지어지지 않거나 Comment로 이야기를 나누기 어렵다는 생각이 들 경우 회의날짜에 회의를 진행한다.

**Comment by dkfma4915** [comment]
전 괜찮은거같아요~!!

**Comment by jongfeel** [comment]
이런 방식 아주 좋습니다.

꼭 모여서 얘기해야할게 생각보다 많지 않기 때문에
필요할 때 마다 의견을 제시하고 빨리 결정이 될 수 있는 거면 issue로 의견 나누고 close 하는게 훨씬 나아요.

그러면 남은 issue에 대해 논의할 내용이 있다면 그때 리뷰 미팅을 해보면 좋을 것 같고요.
오늘 같은 경우는 어떻게 해야 할지 정해야 할 거 같습니다.
가이드를 드려보면

---

리뷰미팅날 오후 6시 까지의 issue 상태를 확인
- 논의할 이슈 있으면 그날 오후 11시에 온라인 리뷰 미팅 진행
- 논의할 이슈 없으면 다음주 같은 시간 혹은 (최소) 1주일 이후 가능한 날짜로 미팅 시간 옮김

**Comment by fora22** [comment]
@kiJiyeon  확인 부탁~

---
시간의 자율성(?) - (저녁에 뭐뭐 해야겠다)을 위해서, 리뷰 미팅날 오후 6시보다는 그 전날 밤 12시에 Issue 상태를 확인하는게 어떨까요?

**Comment by kiJiyeon** [comment]
확인했습니다~~ 좋은 방법이네요!!

**Comment by jongfeel** [comment]
> @kiJiyeon 확인 부탁~
> 
> 시간의 자율성(?) - (저녁에 뭐뭐 해야겠다)을 위해서, 리뷰 미팅날 오후 6시보다는 그 전날 밤 12시에 Issue 상태를 확인하는게 어떨까요?

이것도 좋습니다.
사실 저는 여러분들의 agile한 진행을 돕기 위해 미팅 당일 오후 6시 까지를 고려해드렸는데
전날 12시면 억지로 미팅 하려고 이슈 만드는 일은 안할 수도 있겠네요.

그러면 오늘은 리뷰 미팅이 진행되는 걸까요???
@kiJiyeon @dkfma4915 @fora22

**Comment by dkfma4915** [comment]
> > @kiJiyeon 확인 부탁~
> > 시간의 자율성(?) - (저녁에 뭐뭐 해야겠다)을 위해서, 리뷰 미팅날 오후 6시보다는 그 전날 밤 12시에 Issue 상태를 확인하는게 어떨까요?
> 
> 이것도 좋습니다.
> 사실 저는 여러분들의 agile한 진행을 돕기 위해 미팅 당일 오후 6시 까지를 고려해드렸는데
> 전날 12시면 억지로 미팅 하려고 이슈 만드는 일은 안할 수도 있겠네요.
> 
> 그러면 오늘은 리뷰 미팅이 진행되는 걸까요???
> @kiJiyeon @dkfma4915 @fora22

오늘 미팅은 진행하지않고 다음주 미팅 같은 시간으로 정하면 될거같아요!

**Comment by fora22** [comment]
> 오늘 미팅은 진행하지않고 다음주 미팅 같은 시간으로 정하면 될거같아요!

담주 미팅 같은 시간에는 다른 미팅이 있어서 다른날짜 희망합니다!
근데 제가 22~24가 여행일정이 있어서 주말에 혹시 가능할까요?

**Comment by jongfeel** [comment]
주말(19일)에 오후 시간 됩니다.

대원님, 지연님이 만약 온라인 모각코에 참여한다면 시간 따로 빼지 말고 바로 12시에 진행하는 것도 좋은 작전 같습니다.
(적어도 1시간 이내에 끝낸다는 조건이라면요)

**Comment by dkfma4915** [comment]
> 주말(19일)에 오후 시간 됩니다.
> 
> 대원님, 지연님이 만약 온라인 모각코에 참여한다면 시간 따로 빼지 말고 바로 12시에 진행하는 것도 좋은 작전 같습니다.
> (적어도 1시간 이내에 끝낸다는 조건이라면요)

네! 19일 12시 모두 괜찮다고해서 19일 12시로 다음 미팅 정해두면 될것같아요 ㅎㅎ

**Comment by fora22** [comment]
Meeting Rule 변경 -> 프로젝트 README 확인
