### ISSUE TITLE
Pull Request를 사용해봤으면 좋겠습니다.

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#18]
Pull Request는 Github의 가장 중요(?)한 기능 중 하나인데 익숙해지기 어렵습니다. 왜냐하면
- Branch 개념의 이해 부족 
- merge의 사용에 능숙해지기 어려움
- 생전 처음 해보는 Online Review
---
그래도 어렵지만 해봤으면 좋겠습니다.
- 모르는 게 생기면 코드를 보며 Online으로 얘기해볼 수 있음
- 생각도 못했던 의외의 팁들이 자연스럽게 공유됨
- 뭐든 자주 대화하면 좋다(온라인이든 오프라인이든 소통이 중요)
## 그래서
Main Page  올리기로 한거를 각자 수요일(12/16)까지 PR을 올려봤으면 합니다.
그리고 꼭 Review Point 를 올릴 것!
### Review Point
code만 달랑 올라오면 뭘 봐달라는지 모르니 어떤 부분을 중점으로 봐줬으면 좋겠다고 Point를 올려야 함
- 코드의 효율성(속도, 메모리 효율)
- 리팩토링 -> 난잡한 코드를 객체(class)나 함수(function)의 사용으로 이쁘게 만든다던지
  - 리팩토링(Refactoring)이란 : 기능은 변경되지 않고 코드를 개선하는 작업을 말함.
- 이거 웹페이지 렌더링 하면 '이러한 디자인 나왔는데 이 디자인 어때?' 도 괜찮음
- 자랑도 괜찮음 ㅇㅇ

**Comment by kiJiyeon** [comment]
확인했습니당

**Comment by dkfma4915** [comment]
예압 확인요
