### ISSUE TITLE
Branch에 Merge 를 자주 했으면 좋겠당

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#19]
- 예전 경험인데 main branch하고 Develope branch가 있었음 
- 대부분 Develope에서 작업했는데, 가끔 branch main인거 확인안하고 작업해버림
- 나중에 알았지만 별 문제 없는 것 같아서 그냥 진행함
- 조금 기간이 지남
- main merge했더니 Conflict가 45개정도 생김
- 봤더니 폴더 위치 변경한답시고 main이랑 Develope이랑 서로 다르게 해놔서 엉킴
- 45개가 다 코드파일이 아니고 환경 파일임
  - Visual Studio의 솔루션 파일이라던가
  - binary 파일이라던가
- 어디서 부터 고쳐야 될지 몰라서 결국 코드내용만 복사해서 새로 레포지토리 팜
## 결론은
- main branch에 merge 자주했음 좋겠다.
  - 소규모 conflict는 해결하기 쉬움
  - 근데 커밋내역이 많아지고 마지막으로 merge한 기간이 길수록 conflict는 많아질 수도 있음
 - 자주의 기준은 각자마다 다르겠지만 적어도 2번 미팅 주기로 하면 좋겠다 싶음(우리는 1주일에 2번하니까).

**Comment by kiJiyeon** [comment]
확인~!
---
근데 merge를 언제 해야하는지 아직 감이 안잡혀 ㅠㅠ

**Comment by fora22** [comment]
> ## 확인~!
> 근데 merge를 언제 해야하는지 아직 감이 안잡혀 ㅠㅠ

간단하게 말하면 미팅 2번하면 그중에 1번? 어림잡아 1주일 단위!!

**Comment by dkfma4915** [comment]
확인요~~ 지금 각자 하고 있는 작업들도 가끔씩 merge를 해달라는거지???!

**Comment by fora22** [comment]
> 확인요~~ 지금 각자 하고 있는 작업들도 가끔씩 merge를 해달라는거지???!

ㅇㅇ 
- 무언가 구현이 완료 되었거나
- 마지막으로 merge한지 1주일 지났다거나..?

**Comment by dkfma4915** [comment]
> > 확인요~~ 지금 각자 하고 있는 작업들도 가끔씩 merge를 해달라는거지???!
> 
> ㅇㅇ
> 
> * 무언가 구현이 완료 되었거나
> * 마지막으로 merge한지 1주일 지났다거나..?

네엡~~
