### ISSUE TITLE
Team Rule

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#2]
1. Branch name 
2. Folder rule

**Comment by fora22** [comment]
# 노션과 깃허브의 사용
어느 파일은 노션에 있고 어느 내용은 깃허브에 있는걸 방지하고자 Senior Project는 과감하게 삭제할 예정
- 모든 논의와 의견은 깃허브에 기록할 것
- 다만 회의록은 노션 별도 페이지가 있으니 노션에 적어 둔 후 나중에 깃허브로 옮길 예정

**Comment by fora22** [comment]
# Branch 및 폴더에 관하여
## 폴더에 관하여
- 폴더는 각자 개인 폴더를 나눠가져서 작업한다.
  - ex) `fora22`, `Armful`, `jiyeon`, `jongfeel` [예시 링크](https://github.com/JEoN-Ha/Senior-Project)
  - 회의 결과 후 변경 예정
## Branch의 경우
- `[닉네임]/Develope`을 기본 branch로 만들어 각자 작업한다.
  - `fora22/Develope`
- 기능을 추가하거나 만들때는 `[닉네임]/Feature/[기능명]` branch를 만들어 작업한 뒤, 완료 후 PR(Pull Request) 혹은 merge한다.
  - ex) `fora22/Feature/Index`, `fora22/Feature/payment_page` 등

**Comment by fora22** [comment]
README로 옮기도록 함
https://github.com/JEoN-Ha/Senior-Project
