### ISSUE TITLE
데이터 저장 DB에 관하여

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#27]
# 데이터를 저장할 DB가 필요함
DB에 저장할 데이터(지금 생각나는 것)
- 사용자 Login 데이터
- 음식 메뉴 데이터
## DB 추천
들어본 것은 mysql 정도이긴 한데 DB쪽은 거의 본적이 없어서 좋은 의견 있으면 알려주세요 ㅠㅠ @jongfeel

**Comment by jongfeel** [comment]
처음이면 MySql 써보면 좋습니다.

어떤 DB를 쓰면 좋냐에 대한 답은 누가 알려주는 게 아니라,
내가 어떤 DB를 써야 하는지에 대한 이유를 찾을 수 있으면 됩니다.

**Comment by fora22** [comment]
네 알겠습니다~ 
DB는 지연이 중심으로 알아보고 진행할 것 같습니다~ https://github.com/JEoN-Ha/Senior-Project/issues/21#issuecomment-747226642
