### ISSUE TITLE
Review Meeting Issue 발행 주기를 늘리겠습니다.

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#29]
# 너무 정신없다.
회의가 2~3일마다 있는데(온라인, 오프라인 한 번씩)
각 회의마다 Issue를 발행하니 생각한 문제점, 의논점을 적어놓고 의논할 시간이 부족한 것 같음

또 회의 전날에 급하게 Issue들을 올리게 됨(오늘같이).
# 그래서
- 멘토님과 하는 Online 미팅에서만 Issue를 발행했으면 좋겠음
# 그럼 Offline 미팅은?
- 오프라인 미팅 때는 review meeting에 있는 Issue들을 우선적으로 실행 및 의논함
- 해결안되면 다음 Online 미팅으로 넘어가짐
- 해결된 이슈는 체크
# 그리고 추가로(사실 사소한건데)
1. Online meeting만 Issue올리면 2씩 건너뜀
   - 4th -> 6th 식(Offline meeting은 Issue 안올려서)
   - 그럼 4th -> 5th 만 셀까?
   - 그럼 전체 회의 수를 한 눈에 못알아봄
2. 사실 3rd meeting이 4번째 미팅임
     - 1.5st meeting 때문인데
   - 불---편 함
   - 다음 미팅을 4th로 할지 5th로 할지 정했으면 좋겠음
     - 사실 원하는건 5th
     - 대신 그럼 1st, 1.5st, 2nd, 3rd는 이름 바꿔야 함 ㅎㅎ;;
     - 죄송..허헣...ㅎ;;
 
# Go to Conference
#21

**Comment by jongfeel** [comment]
기준은 팀원들이 합의한대로 하면 좋을 것 같아요.

**Comment by fora22** [comment]
네! 오늘 이야기 나눴습니당.
# 합의 내용
- Online Meeting에만 Issue를 올리고 번호는 Online 미팅에 맞춰서 올린다(Offline은 count 안 함).
- 전체 회의 수는 곱하기 2하면 얼추 맞을 듯.
- 1.5st -> 2th로 하고 나머지 meeting도 숫자를 1씩 올리도록 함.  #8
