### ISSUE TITLE
README를 읽고 조금 더 좋은 아이디어를 떠올렸습니다.

### ISSUE THREAD

**Issue by jongfeel** [JEoN-Ha/Senior-Project#3]
### 주문 및 결제

- 웹페이지 이용 까지는 맞음
- 앱개발 까지는 어려우므로 모바일 웹페이지도 사용할 수 있도록 고려
- 그러면 처음부터 반응형 웹페이지로 만들면 좋지 않을까 하는 생각입니다.

### 음식 조리 시작

- 분석한 README의 내용: 차량 번호 인식 후 주문 내역을 구매자에게 전송 후 음식 조리 시작
- 저의 제안 내용
  - 미리 웹페이지에서 주문 했으므로 조리 시간 및 픽업 예상 시간이 나오면 좋을 것 같음
  - 그래야 구매자가 시간에 맞춰서 드라이브 스루 매장으로 감
  - 차량 번호를 인식하면 웹페이지에서 주문한 고객인지 확인
  - 음식이 아직 안나왔다면? 대충 대기시간 알려줌
  - 음식이 나왔다면? 콘테이너 벨트 동작 => 음식 전달 
- 제안 아이디어 by 스타벅스 사이렌 오더
  - 사이렌 오더로 주문하면 몇 번째 음료로 제조하는지 알려줌 (몇 분 걸리는지는 안알려주지만 자주 사용하다 보면 감이 옴)
  - 매일 아침 일정한 시간에 주문하다 보면 언제쯤 주문을 걸어 놓고 매장에 방문하면 내 커피가 나와 있을 것이라는 걸 알게 되므로 그렇게 주문하게 되어 있음 => 저의 경우는 지하철 내려서 스타벅스 매장에 걸어가기 까지의 시간이므로 내리기 전에 사이렌 오더로 주문 걸어 놓음.

**Comment by dkfma4915** [comment]
오 픽업 예상 시간 의견 좋은 것 같아요 ! 사이렌 오더를 사용안해봐서 몇번째 음료도 알려주는지는 몰랐네요!
반응형 웹페이지도 고려해보겠습니다 ㅎㅎ

**Comment by fora22** [comment]
좋은 의견 감사합니다. 

혹시 사용자가 픽업시간을 입력하면 그거에 맞게 음식 조리를 하는 것에 대해서는 어떻게 생각하시나용? ㅎㅎ

**Comment by jongfeel** [comment]
주문을 12시 30분에 하고
픽업을 2시에 한다고 한다면

조리 시간이 20분 걸린다고 했을 때
1시 40분에 조리를 시작하는 거죠.

이게 맞다면 괜찮은 아이디어입니다.

**Comment by fora22** [comment]
> 주문을 12시 30분에 하고
> 픽업을 2시에 한다고 한다면
> 
> 조리 시간이 20분 걸린다고 했을 때
> 1시 40분에 조리를 시작하는 거죠.
> 
> 이게 맞다면 괜찮은 아이디어입니다.

넵 맞습니다 ㅎㅎ 좋은 의견 정말 감사합니다 ㅎㅎ
