### ISSUE TITLE
[긴급] Server 구축 오류 및 진행방향에 대해서

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#40]
![image](https://user-images.githubusercontent.com/48875566/102717049-1f1f6680-4323-11eb-80c4-54335269c076.png)
![image](https://user-images.githubusercontent.com/48875566/102717572-93a7d480-4326-11eb-84ab-4bc13f2194af.png)
https://github.com/JEoN-Ha/Senior-Project/issues/38#issuecomment-748610176 이거 보고 물어보는건데 혹시 이런 현상으로 오류뜨는 상황이 발생하니??
# 만약 둘 다 지금 그렇다면
조금 알아보니까 [여기](https://dev-dain.tistory.com/62) 포스팅 한게 2020년 7월에 올라왔는데 그때까진 Github Student Developer Pack(학생용 지원)에는 AWS Educate 가 있었음.

근데 [지금 찾아보면](https://education.github.com/pack?sort=popularity&tag=Cloud) AWS가 없음(Educate 서비스가 약화되거나 무언가 문제가 생긴듯..?)

그래서 많이 늦지 않았다면 Azure에서 작업하는게 낫지않을까는 생각이 듬.

# 찾아보니까
- 참고할 자료는 있긴 있음
- 대신 대부분이 영어자료임
## 참고자료
- [Azure의 Node.js](https://azure.microsoft.com/ko-kr/develop/nodejs/)
- [Azure Database for MySQL](https://azure.microsoft.com/ko-kr/services/mysql/?&ef_id=Cj0KCQiAifz-BRDjARIsAEElyGL5TGahFBaEHAoi22dplMiA-4yC7XqxDHshEuw75e6ofucNiT1JMbUaAkmZEALw_wcB:G:s&OCID=AID2100068_SEM_Cj0KCQiAifz-BRDjARIsAEElyGL5TGahFBaEHAoi22dplMiA-4yC7XqxDHshEuw75e6ofucNiT1JMbUaAkmZEALw_wcB:G:s&gclid=Cj0KCQiAifz-BRDjARIsAEElyGL5TGahFBaEHAoi22dplMiA-4yC7XqxDHshEuw75e6ofucNiT1JMbUaAkmZEALw_wcB)
- [React 및 Azure Cosmos DB에서 MongoDB 앱 만들기](https://docs.microsoft.com/ko-kr/azure/cosmos-db/tutorial-develop-mongodb-react)
- [reactjs - Azure App Service에 React Webpack 웹 앱을 어떻게](https://stackoverrun.com/ko/q/11225310)

**Comment by kiJiyeon** [comment]
> #38 (comment) 이거 보고 물어보는건데 혹시 이런 현상으로 오류뜨는 상황이 발생하니?? 

나는  EC2 사용해서 웹서버 올리는데 오류 남!!! 

1. #38 (comment)에 올라와있는 링크에서 예제 실습했는데,  글 마지막 부분처럼 웹 페이지가 떠야하는데,  나는 404 Error가 뜸 ㅜㅜ
<img src ="https://user-images.githubusercontent.com/48858836/102728439-400da900-436f-11eb-842a-63a985a959e2.png" width = "60%">

2. 누가 블로그 댓글에 나랑 같은 문제 생겼대서 거기에 [달린 답글 내용](https://medium.com/@dbwlsldk0947/%EC%9E%98-%EB%B4%A4%EC%8A%B5%EB%8B%88%EB%8B%A4-%EA%B7%BC%EB%8D%B0-%EC%A0%9C%EA%B0%80-%EB%94%B0%EB%9D%BC%ED%95%98%EB%8B%A4%EA%B0%80-%EB%A7%88%EC%A7%80%EB%A7%89%EC%97%90-index-html%EC%9D%84-ae0d594d271b) 통해서 해결해 보려고 했는데 실패!

**Comment by kiJiyeon** [comment]
나도 어제 하면서 Azure를 해보는건 어떨까 라는 생각들었쓰,,,,,,,,

**Comment by fora22** [comment]
Azure로 진행해봐??

**Comment by kiJiyeon** [comment]
Azure로 진행해보고 어떤지 느껴봐야겠어 !!
