### ISSUE TITLE
내용 정리에 관하여

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#42]
- https://github.com/JEoN-Ha/Senior-Project/wiki/React-Redux-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0
- https://github.com/JEoN-Ha/Senior-Project/wiki/MySQL-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0
- https://github.com/JEoN-Ha/Senior-Project/wiki/MySQL-Syntax

위 wiki들을 보면 내용 정리할 때 너무 `하는 방법`에만 치중되어 있다는 생각이 듬.

예를 들어 Redux의 경우 Redux가 무엇에 사용되고 왜 사용되는지에 대해 설명되어 있지 않고 설치하는 방법만 써져있음.

이러면 모르는 입장에서는 나에게 필요한지 아닌지 판단 할 수 없고 다시 redux에 대해 알아봐야 하는 상황이 생김. 중복으로 찾아보는 상황을 방지하기 위해서 정리하는 건데 그 취지가 정확히 반영되지 않는다는 생각이 듬. 

Mysql 같은 경우에도 Table이란 무엇인지 CRUD가 무엇인지 개념에 대한 설명이 부족해 보임.

# 그래서
다음에 Wiki 작성 혹은 문서 정리 때 반영해주길 바람.

**Comment by dkfma4915** [comment]
참고로 아직 강의를 다 안들어서 설치하기 밖에 없는 것!! (설치하기만 미리 적어두고 한번에 정리하려고 했던 것이었음)
내용 추가 예정이라고 쓰려다가 말았는데,, 쓸걸 그랬네
그게 끝은 아니였어!! 
오빠가 말한 의견은 반영하도록 하겠습니다~~!

**Comment by kiJiyeon** [comment]
확인~~ 반영하겠삼!!
