### ISSUE TITLE
React-Redux 사용에 관한 논의

### ISSUE THREAD

**Issue by dkfma4915** [JEoN-Ha/Senior-Project#44]
# React-Redux 사용 여부에 관해..
멘토님의 추천도 있었고 조금씩 state가 많아지면서 헷갈리는 것도 생겨서 상태 관리가 필요하겠다 라는 생각이 들어
생활코딩의 React-Redux 강의를 완강함. 하지만 이제 React에 아주 조금 익숙(?)해졌는데 React-Redux를 도입해서 지금까지 짰던 것을 수정하려하니 어디서부터 손봐야할지 감이 안잡힘,, 아직 React-Redux가 낯설어서 수정하는데도 시간이 걸릴거같다는 생각이 들었음! 그래서 의견을 묻고 싶은데 아래 2개 중에 뭐가 나을까!

## 1. 시간이 걸리더라도 지금까지 짠 코드들을 React-Redux로 바꾸고 진행한다.
- 내가 생각한 단점 : 지연,대원은 React-Redux로 바꾼 코드를 바로 당장 이해하기 어렵게 됨 (나중에 생활코딩 강의를 들어야 이해하기 쉬울 것으로 예상)
- 장점 : 제대로 바꾸기만 한다면 상태 관리가 편해질 것. 사실 가장 이상적인 방법이긴함,,

## 2. 일단 하던대로 React로 진행하고 시간이 남을 경우 React-Redux로 바꾼다.
- 아직 진짜 state때문에 엄~~청 불편하진 않으므로 Redux로 인해서 더 복잡하게 생각할바엔 그냥 진행해도 되겠다는 생각도 들었음

# 참고 자료
[생활코딩 React Redux 소개 영상 (wiki에 react-redux 상단에 정리해놓은 내용과 비슷)](https://www.youtube.com/watch?v=fkNdsUVBksw&list=PLuHgQVnccGMDuVdsGtH1_452MtRxALb_7&index=1)
[Redux의 장단점](https://ibrahimovic.tistory.com/31)
영상은 5분이내라 얼른 들어도 되고 [wiki](https://github.com/JEoN-Ha/Senior-Project/wiki/React-Redux-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0#redux%EB%9E%80)를 읽어도 됩니당~

**Comment by fora22** [comment]
Redux로 사용하면 어떤게 편해지는지에 대한 설명이나 예시가 필요할 듯!

- 직접 작성도 좋고 인터넷 링크도 괜찮음!

**Comment by dkfma4915** [comment]
> Redux로 사용하면 어떤게 편해지는지에 대한 설명이나 예시가 필요할 듯!
> 
> * 직접 작성도 좋고 인터넷 링크도 괜찮음!

오케이 바로 수정했어!!

**Comment by fora22** [comment]
오우 지금은 못볼듯한데 내일 comment해도 될까??

**Comment by dkfma4915** [comment]
> 오우 지금은 못볼듯한데 내일 comment해도 될까??
응응 당근~

**Comment by kiJiyeon** [comment]
나도 내일 보고 코멘트칠게~!!!

**Comment by fora22** [comment]
**나는 Redux 사용에 찬성 한 표!**

# 이유는?
## 나의 개인 경험
main page 연습할 때 'props'와 'state'간의 정보전달 때문에 시간이 많이 소비됐던 경험이 있음. 간단한 컴포넌트 추가였지만 컴포넌트 아래로 연속 2개가 묶여있는 컴포넌트다 보니 App의 state 바꿀 때 엄청 애먹었던 경험이 있음. Redux 컨셉이 잘 이루어진다면 훨씬 나아보임.

## 개발의 편이성 및 가독성 증가
React 할 때 가장 골치아팠던게 태그에 있는 정의 함수 들임.

함수에 이름이 정해져 있지 않고(물론 속성 이름은 있지만) 태그마다 각각 있기 때문에 코드 알아보기가 힘들었음(wiki의 예제 코드 보고 난 생각). 나중에 본인 혹은 지연이가 봐도 알기 쉬울려면 Redux 사용이 꼭 필요하다 생각함.

## 유지보수의 편이성
이후에 일어날지 안일어날지 모르겠지만 졸업작품중의 피드백 때문에 기능변경 크게는 페이지 구조 변경이 일어날 수 있음(충분히 있을법함). 이때 가독성 높은 코드는 유지 보수면에서도 메리트가 높다 판단됨.

현재 시간을 더 들여야 한다는 단점이 있지만 초기투자로 얻는 이득이 더 클 것 같아서 본인은 찬성합니다.

**Comment by kiJiyeon** [comment]
나도 **1번 React-Redux로 바꾸고 진행한다.**에 한표!!

## 이유는 

> React는 작은 컴포넌트들도 나뉘어져 있다. 각각의 컴포넌트에서 필요한 데이터를 스스로 호출한다고 가정해보면, 컴포넌트 개수 이상의 API 호출이 일어날 것이다. 만약 A라는 컴포넌트와 B라는 컴포넌트에서 일부 중복되는 데이터를 쓰고 있더라도, A와 B의 상태는 서로 공유되지 않기 때문에 불필요한 호출을 시도해야 한다.
> 
> Redux를 사용하면 한번 호출된 데이터는 store에 저장된다. 마치 창고에 데이터를 적재해둔것과 같다. 컴포넌트들은 언제든 이 창고에 들려 필요한 데이터만 가지고 가면 된다. 굉장히 효율적이다. 또한, 단 하나의 진실의 근원(single source of truth)을 보장한다. 모든 컴포넌트는 동일한 데이터를 가져다 쓴다. 이렇게 하면 모든 UI가 일관된 내용을 유지할 수 있다.

> 출처: https://ibrahimovic.tistory.com/31 [Web Standard]

이부분을 보니까 저번에 아름이가 올린 #41 의 두번째 문제 같은 상황이 생기는 걸 방지할 수있겠다는 생각이 들어!!! 

그리고 대원오빠 말처럼 초기 시간 투자로 탄탄하게 만들어놔야 나중에 멘탈 박살 나는 상황이 조금이라도 덜 생기지 않을까 하는생각~!

**Comment by dkfma4915** [comment]
1번으로 결정 !!
그럼 오늘부터 일단 지금까지 짠 코드를 바꿔보도록 할게~~~
