### ISSUE TITLE
DB-Web 서버 연결에 문제 

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#50]
어제 오늘 DB-WEB연동하는걸 다시하고있는데, 문제 해결 발법을 모르겠어서 올림!

## Reference
1. Azure에서 제공하는 매뉴얼
[기존 Azure App Service를 Azure Database for MySQL 서버에 연결](https://docs.microsoft.com/ko-kr/azure/mysql/howto-connect-webapp)

2. 블로그 예제(Express 사용)
[React와 Express연동하기 1](https://coding-hyeok.tistory.com/21?category=842997)
[React와 Express연동하기 2](https://coding-hyeok.tistory.com/22?category=842997)
[React - Mysql 연결하기(데이터 저장)](https://coding-hyeok.tistory.com/23?category=842997)
[React - mysql연결 (데이터불러오기)](https://coding-hyeok.tistory.com/24?category=842997)

# 본문
Referecne 2번의 블로그 예제 따라하면서, `server.js`코드에  
![image](https://user-images.githubusercontent.com/48858836/103349952-c3eb3200-4ae1-11eb-9779-656df7867b3d.png)

![image](https://user-images.githubusercontent.com/48858836/103349960-cea5c700-4ae1-11eb-89af-262b48edc5c6.png)

이 부분을 Azure 연결문자열(node.js부분) 복붙해서 실행을 시키면 되지 않을까?라는 생각이 들어서  고쳐봤는데,(`App.js` 코드는 블로그 예제 코드랑 동일)

 계속 아래랑 같은 오류가 뜸...

![image](https://user-images.githubusercontent.com/48858836/103350127-44aa2e00-4ae2-11eb-827e-38a613ad5075.png)

# 그래서 문제는,

1.  [MySQL용 Azure Database에 안전하게 연결하기 위한 사용자 애플리케이션의 SSL 연결 구성](https://docs.microsoft.com/ko-kr/azure/mysql/howto-configure-ssl) 을 참고해서 해결해보려고 했는데, 똑같이 따라해봐도 계속 에러가 뜸

2.  그리고 첫번째 사진에 있는 `ssl : {ca:fs.readFileSync({ca-cert filename})}`을 어떻게 작성해야하는지를 모르겠음

찾아보니까 방법이 여러가지가 있음. 근데 어떤 파일을 넣는건지도 잘 모르겠음... [MySQL용 Azure Database에 안전하게 연결하기 위한 사용자 애플리케이션의 SSL 연결 구성](https://docs.microsoft.com/ko-kr/azure/mysql/howto-configure-ssl) 참고해서 똑같이 했는데도 안됨 ㅠㅠ

```
 ssl:{ca:fs.readFileSync({"ca-cert": filename})}
```
>[출처](https://github.com/MicrosoftDocs/azure-docs/issues/37639)

```

var mysql  = require('mysql');
var fs     = require('fs');

var connection = mysql.createConnection({
     host     : 'localhost',
     user     : 'me',
     password : 'secret',
     database : 'my_db',
     ssl      : {
           ca   : fs.readFileSync('./ssl/server-ca.pem'), // should be enough for AWS
           key  : fs.readFileSync('./ssl/client-key.pem'), // required for google mysql cloud db
           cert : fs.readFileSync('./ssl/client-cert.pem'), // required for google mysql cloud db
     }
});
```
[출처](https://stackoverrun.com/ko/q/34361)

**Comment by fora22** [comment]
작업 환경이 어디에 있죠??

**Comment by fora22** [comment]
음 코드랑 환경을 다 봐야 알 것 같은데...코드조각만 보내주면 잘 모르겠음;;

**Comment by fora22** [comment]
![image](https://user-images.githubusercontent.com/48875566/103395977-11b07a80-4b74-11eb-9e88-2b66a203bb24.png)

[MySQL용 Azure Database에 안전하게 연결하기 위한 사용자 애플리케이션의 SSL 연결 구성](https://docs.microsoft.com/ko-kr/azure/mysql/howto-configure-ssl)
일단 추측되는건 빨간색 네모의 링크를 클릭하면 파일을 다운받을 수 있음. 이 파일을 `filename`에 넣는 것 같음.

경로는 상대경로로 아마 작업환경 루트 폴더에서  `ssl`폴더를 만들면 `./ssl/{filename}`식으로 하면 될 듯..?

참고로 알고 있을수도 있긴한데 SSL이 왜 쓰이는지에 대해 알고 있으면 좋을 것 같음 -> [참고](https://wiki.kldp.org/HOWTO/html/SSL-Certificates-HOWTO/x70.html)

**Comment by kiJiyeon** [comment]
일단 바로위에 있는 코멘트대로 해보고 안되면 다시 레포지토리 공유할게!! 감사!!!

**Comment by fora22** [comment]
https://codefooo.github.io/app-azure/

중요한 내용(?)을 찾은것 같음. 아직 나도 해보지는 않았는데 위 링크 가보면 이렇게 써져 있음.

> `Enforce SSL connection`은 disable 해야 나중에 애플리케이션이 데이터베이스에 접속할 때 문제가 발생하지 않습니다.

확인바람! @kiJiyeon

**Comment by kiJiyeon** [comment]
> https://codefooo.github.io/app-azure/
> 
> 중요한 내용(?)을 찾은것 같음. 아직 나도 해보지는 않았는데 위 링크 가보면 이렇게 써져 있음.
> 
> > `Enforce SSL connection`은 disable 해야 나중에 애플리케이션이 데이터베이스에 접속할 때 문제가 발생하지 않습니다.
> 
> 확인바람! @kiJiyeon

아직 읽어보진 않았지만 disable해야 문제가 발생하지 않는다니,,,,, 충격과 공포,,,,

**Comment by fora22** [comment]
참고로 난 [위키](https://github.com/JEoN-Ha/Senior-Project/wiki/Azure-Web-App-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0) 보면서 `로컬 git 레포지토리`로 하고 있는데 반영이 안됨

### 지연이와 다른점
Test_React 레포지토리로 이미 `.git` 파일이 있는 상태였음. 그래서 그런지 push해도 remote랑 다르다고 push가 안됨.
Pull을 해서 push를 해봤음(중간에 `yarn build`를 해서 build 파일만 push 해봄 허나 여전히 동작 안함...
### 생각나는 문제점
- 기존 레포지토리의 변경점을 push하는거라 기존 파일은 안들어가고 build 폴더만 들어갔을 가능성이 있음
  - 허나 해결 방법을 모르겠음

**Comment by kiJiyeon** [comment]
> 참고로 난 [위키](https://github.com/JEoN-Ha/Senior-Project/wiki/Azure-Web-App-%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0) 보면서 `로컬 git 레포지토리`로 하고 있는데 반영이 안됨
> 
> ### 지연이와 다른점
> Test_React 레포지토리로 이미 `.git` 파일이 있는 상태였음. 그래서 그런지 push해도 remote랑 다르다고 push가 안됨.
> Pull을 해서 push를 해봤음(중간에 `yarn build`를 해서 build 파일만 push 해봄 허나 여전히 동작 안함...
> 
> ### 생각나는 문제점
> * 기존 레포지토리의 변경점을 push하는거라 기존 파일은 안들어가고 build 폴더만 들어갔을 가능성이 있음
>   
>   * 허나 해결 방법을 모르겠음

나도 한번 push 하고 다시 Push할 때 이런 오류 떠서 [참고](https://aonee.tistory.com/14) 보고 해결해 보려고 했었는데, 결국 해결 못하고 새로 만들었음 ㅠㅠ  ( 간단한예제라서)

**Comment by kiJiyeon** [comment]
그리고 나 방금 우연히 
![image](https://user-images.githubusercontent.com/48858836/103407735-0e80b300-4ba3-11eb-9adc-b21359138e5c.png)이거 발견했는데 해보고 어떻게 됐는지 알려주겠음!
 
참고로, 리소스 만들기에 `app services` 검색하고 스크롤 내리면 있어

**Comment by fora22** [comment]
> 그리고 나 방금 우연히
> ![image](https://user-images.githubusercontent.com/48858836/103407735-0e80b300-4ba3-11eb-9adc-b21359138e5c.png)
> 이거 발견했는데 해보고 어떻게 됐는지 알려주겠음!
> 
> 참고로, 리소스 만들기에 `app services` 검색하고 스크롤 내리면 있어

머야 이거;; 지금 확인했네...

일단 ㅇㅋ 내일 해볼게
