### ISSUE TITLE
스타일링을 지정할 때 `.css` 파일로 할 것인지 변수로 할 것인지

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#52]
# Styling
1월 되면 진행할거긴 한데 원래 우리 모바일환경을 고려하면 flexbox라는 기능을 이용해야 함. px은 갠적으로 낡은 방식(?)이라고 생각함. 그래서 스타일링에 크게 신경 안썼으면 함(이미 알고있어서 그런 것 같긴 하지만).

하지만 **중요한 것은 이후에 스타일링을 지정할 때 `.css` 파일로 할 것인지 변수로 할 것인지에 대한 논의가 필요할 듯**. 

사실 너무 디테일해서 작업자가 그냥 결정한다는 선택지도 있음. 새로 Issue 올려 투표(?) 진행해보겠음.

Reference from https://github.com/JEoN-Ha/Senior-Project/issues/51#issuecomment-752860554

---

그래서 댓글로 투표 해주셨으면 좋겠습니다.
1. 작업자가 결정한다. -> 작업자가 2번 3번 중 고민해보고 적용한다.
2. 변수로 지정한다.
3. 최대한 css파일을 활용하고 동적으로 변하는 style 만 변수를 활용한다.

**Comment by dkfma4915** [comment]
3번!!

**Comment by fora22** [comment]
> 3번!!
> 뭔가 px를 계속 쓰기엔 한계가 있을거같음
아 혹시 오해(?)가 있을까봐 issue 내용 수정함. 확인바람~

---

난 1번!
취향차이 느낌일거같아서 어느게 더 나은지 판단이 잘 안감!

**Comment by dkfma4915** [comment]
> 난 1번!
> 취향차이 느낌일거같아서 어느게 더 나은지 판단이 잘 안감!

사실 1번도 상관없긴함! 스타일링만 잘 되면 되니까!

**Comment by kiJiyeon** [comment]
나도 1번!! 말그대로 작업자 마음대로 하는게 좋다고 생각

**Comment by jongfeel** [comment]
여기서 제가 뭘 선택하던 1번으로 결정 되겠군요.

사실 저도 1번이긴 합니다.
1번에 추가 조건으로 `내가 이런 방식을 선택한 이유`에 대한 설명이 되면 좋을 것 같습니다.

**Comment by fora22** [comment]
의견 종합해 1번으로 결정!!
> 1번에 추가 조건으로 내가 `이런 방식을 선택한 이유`에 대한 설명이 되면 좋을 것 같습니다.

반영하여 해보도록 하겠습니다~ @jongfeel
