### ISSUE TITLE
How about online meeting move to next week?

### ISSUE THREAD

**Issue by jongfeel** [JEoN-Ha/Senior-Project#53]
어제는 대원님, 세영님의 리뷰 미팅(https://github.com/fora22/CodingTest/issues/56) 때문에 간 자리였는데
사실 이 미팅 얘기보다 여러분들 프로젝트 얘기를 많이 했던 것 같습니다.

그래서,
아직까지 issue나 pull request가 없는 상황이고
또 어제 엄청난 정보를 얘기해 드렸는데 그걸 또 이해하고 진행하는데 시간이 걸릴 수 있으니
내일 모레 예정되어 있는 온라인 미팅을 적절한 날로 이동하는 건 어떨까요?

**Comment by fora22** [comment]
그렇다면 다음주 월요일은 어떠신가요??

**Comment by fora22** [comment]
@kiJiyeon @dkfma4915  두 사람은 괜찮니??

**Comment by dkfma4915** [comment]
> @kiJiyeon @dkfma4915 두 사람은 괜찮니??

좋습니다!!

**Comment by kiJiyeon** [comment]
저도 다음주 월요일 괜찮습니다!!
