### ISSUE TITLE
DB Table 구성도 평가

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#54]
어제 DB Table 구성도에 관해 이야기 해주신걸 참고해서 다시 만들어 보았습니다.

고쳐야 하거나 다른 의견 있으시면 말해주시길 바랍니다! @jongfeel @kiJiyeon @dkfma4915 

- 밑의 사진 둘 다 같은 모델입니다.
- 위에는 Microsoft Acess 활용했고, 밑에는 Google drawing 활용했습니다.

![image](https://user-images.githubusercontent.com/48875566/103607245-c8896d80-4f5b-11eb-8505-2daf8e04eef1.png)

![image](https://user-images.githubusercontent.com/48875566/103607270-d212d580-4f5b-11eb-968d-d8d7bb2ae15e.png)
From https://drive.google.com/file/d/12zIuhSoicgDK5CUhRADcuBDfzR6faOxW/view

**Comment by jongfeel** [comment]
OrderToMenu table
- 지난 논의 때 얘기했는데 count 컬럼을 추가하는게 더 명확할 것 같습니다.
- 한 주문에 한 메뉴의 갯수가 30개면 row가 30개가 되는데 count 컬럼이 있으면 row가 1개만 있어도 되니까요.

**Comment by fora22** [comment]
![image](https://user-images.githubusercontent.com/48875566/103608242-3cc51080-4f5e-11eb-9dff-7299aec85a64.png)

> 지난 논의 때 얘기했는데 count 컬럼을 추가하는게 더 명확할 것 같습니다.

반영했습니다!!

**Comment by dkfma4915** [comment]
고칠점 없는 것 같습니당 ㅎㅅㅎ

**Comment by kiJiyeon** [comment]
나도  고칠거 없다고 생각!

**Comment by fora22** [comment]
확인 완료~
