### ISSUE TITLE
설문조사 폼에 대한 평가 및 의견 반영

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#58]
# 생각하게된 이유
우리 서비스 모델(Untact Drive Thru: UntactDT)은 실제 실행하고 있는 서비스(드라이브-스루)에 즉시 적용할 수 있는 서비스 모델이라고 생각합니다. 이에 대해 아이디어를 생각해 낸 배경 정량적인 근거가 있으면 좋겠다고 생각하여 설문조사 폼을 만들어 보았습니다.

# 설문조사를 통해 얻고 싶은 근거
1. 드라이브 스루의 이용률
2. 차에 탔을 때 마스크 착용률
3. 드라이브 스루에서 비말 접촉의 위험성 인지도

# 설문조사 초기 디자인
![search](https://user-images.githubusercontent.com/48875566/103620035-26c34a00-4f76-11eb-911e-e093d0080e13.jpg)

설문조사 폼은 [여기](https://forms.gle/iwzAyTbxYKWnjh2bA) 있음.

# 그러므로
설문조사 폼에 대해 의견 있거나 평가해주시면 감사하겠습니다.

_Originally posted by @dkfma4915 in https://github.com/JEoN-Ha/Senior-Project/issues/47#issuecomment-754415690_

**Comment by jongfeel** [comment]
설문조사 했습니다

**Comment by fora22** [comment]
> 설문조사 했습니다

추가하거나 삭제했으면 하는 조항같은 것이 있으셨나요?? @jongfeel

**Comment by fora22** [comment]
설문조사 3명이나 5명한테 스타벅스 아메리카노 기프티콘 드린다고 하면 참여율이 높지 않을까? @kiJiyeon @dkfma4915

**Comment by jongfeel** [comment]
> 추가하거나 삭제했으면 하는 문항같은 것이 있으셨나요?? @jongfeel

없었던 것 같아요

**Comment by dkfma4915** [comment]
> 설문조사 3명이나 5명한테 스타벅스 아메리카노 기프티콘 드린다고 하면 참여율이 높지 않을까? @kiJiyeon @dkfma4915

동의!
오류(?)를 발견해서 수정함 [수정한 설문조사 폼](https://forms.gle/F4QcYHYjhE6Evey49)
