### ISSUE TITLE
[긴급] Meeting 요청

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#63]
# [긴급] Meeting 요청
- 참여자: @jongfeel @kiJiyeon @fora22 
- 참여시각 : 2021/01/08 오후 11시
- 내용 : `Unexpected token < in JSON at position 0` 해결에 관한 미팅 
- 본문 : `fetch()` 함수가 동작은 하는데 이상하게 위 오류가 뜹니다. parse 문제라고 알아봤는데 해결 방법이 도무지 모르겠네요. 미팅을 통해 알려주셨으면 좋겠습니다...ㅠ #61 

![image](https://user-images.githubusercontent.com/48875566/103990935-57ed8580-51d5-11eb-86fb-8eef05181a89.png)

[웹 사이트](https://webappmainpage-fora22.azurewebsites.net/)는 여기 있습니다.

**Comment by jongfeel** [comment]
우선 긴급 미팅은 제가 별로 안좋아해서 미팅 참석은 안될 것 같습니다.
그리고 syntax error를 포함한 error 해결을 위한 미팅은 제 개인적으로는 모두에게 시간 낭비이기 떄문에 추천 드리지 않습니다.

정규 미팅이 다음주 월요일로 잡혀 있으니 그 때 리뷰해 보면 될 것 같고요.

이 문제가 해결이 되야 다음 일이 진행되야만 하는 상황이 아니라면
이 문제와 상관 없는 다른 작업을 진행하는게 좋다고 봅니다.

**Comment by fora22** [comment]
> 우선 긴급 미팅은 제가 별로 안좋아해서 미팅 참석은 안될 것 같습니다.
> 그리고 syntax error를 포함한 error 해결을 위한 미팅은 제 개인적으로는 모두에게 시간 낭비이기 떄문에 추천 드리지 않습니다.
> 
> 정규 미팅이 다음주 월요일로 잡혀 있으니 그 때 리뷰해 보면 될 것 같고요.
> 
> 이 문제가 해결이 되야 다음 일이 진행되야만 하는 상황이 아니라면
> 이 문제와 상관 없는 다른 작업을 진행하는게 좋다고 봅니다.

알겠습니다!
