### ISSUE TITLE
Main 폴더에 관하여

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#66]
이번에 우리 프로젝트 이외의 사람에게 도움 받다보니 우리가 작업하는 폴더를 설명해야하는 경우가 있었는데, 이제 WEB 도 한 폴더에서 계속 만들고 있으니 root 폴더(디렉토리)에서 Main 폴더로 만들고 거기에 WEB내용을 Update하는 게 어떨까 싶은데!

동의하면 이모티콘, 의견있으면 comment 해주세요~!

**Comment by kiJiyeon** [comment]
무슨 말인지 잘 이해가 안가!!!!!!!!

**Comment by fora22** [comment]
지금 web이 Armful/.../jeonha_redux에서 작업하고 있잖아. 그걸 우리 레포지토리 루트 폴더로 옮기고, 폴더 이름을 main 혹은 JEoNHa_Web 으로 해서 작업폴더를 지정해놓자는 거얌

**Comment by kiJiyeon** [comment]
아 오케이!! 동의
