### ISSUE TITLE
사전답사(?), 자료조사(?) 제안

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#67]
2021/01/14 목요일에 저희 오프라인 미팅이 있는데, 사전답사(?) 드라이브 스루를 갔다오는게 어떨까요?

최근 드라이브 스루를 몇번 갔다오니 저희가 기존에 생각해 두었던 벨트 형태로는 제공이 힘들 것 같다는 생각이 들어서요. 문제점 및 해결 방법을 말로 설명하기 힘들 것 같습니다. 오프라인 미팅 때 잠시 다녀와서 **머릿속의 청사진**을 일치화 시키는 작업을 했으면 니다.

**Comment by dkfma4915** [comment]
확인요~~~!

**Comment by kiJiyeon** [comment]
확인~
