### ISSUE TITLE
How about use Azure to image processing?

### ISSUE THREAD

**Issue by jongfeel** [JEoN-Ha/Senior-Project#73]
#72 

여기에 논의를 하면 안될 것 같아서 따로 issue를 만들었습니다.

이미지 처리 관련된 링크가 Google Cloud Platform API 로 되어 있던데
Azure 쪽으로 해보시는 건 어떤가요?

요즘 Cloud API들의 성능이나 인식률이 워낙 좋아서 어떤 서비스를 쓰던지 크게 문제되지는 않을 거거든요.

지금 Server hosting에 Azure를 쓰고 있으니까 나중에 요금 청구할 때 한꺼번에 결제하기도 편하고 번거롭지 않을 것 같습니다.

여기에서 OCR이나 Image understanding 쪽을 보면 됩니다.
https://azure.microsoft.com/en-us/services/cognitive-services/computer-vision/

**Comment by fora22** [comment]
음.. GCP로 고른 이유는 한글 예제 혹은 블로그가 더 많아서도 있습니다. Azure는 친절하지 않게 번역된 Microsoft Docs 밖에 없고, GCP 는 블로그 이외에도 유튜브나 다른 자료에 한글 자료들이 많습니다.

Azure 에서 이를 넘어서는 강점이 있다면 Azure로 하겠지만 비슷하다면 GCP가 낫지 않을까요?

**Comment by jongfeel** [comment]
저는 비슷하다면 오히려 하나의 cloud를 선택하고 서비스 관리를 한번에 하는게 더 낫다고 생각했거든요.

저도 회사에서 Azure, AWS, GCP 까지 3개에 개인적으로 IBM까지 해서 총 4개를 쓰는데 관리하기 엄청 귀찮거든요.

나중에 Azure와 GCP 동시에 서비스 관리와 요금 관리, 문서 관리를 할 계획이면 GCP도 상관 없습니다.

**Comment by fora22** [comment]
> 저는 비슷하다면 오히려 하나의 cloud를 선택하고 서비스 관리를 한번에 하는게 더 낫다고 생각했거든요.
> 
> 저도 회사에서 Azure, AWS, GCP 까지 3개에 개인적으로 IBM까지 해서 총 4개를 쓰는데 관리하기 엄청 귀찮거든요.
>
> 나중에 Azure와 GCP 동시에 서비스 관리와 요금 관리, 문서 관리를 할 계획이면 GCP도 상관 없습니다.

저 혼자 결정할 수 있는 부분은 아닌 것 같네요ㅋㅋ 제 생각엔 나중에 시간적으로 여유가 된다면, GCP에도 Web 및 DB 서버를 올려서 통합하도록 진행 하는게 좋을 것  같습니다. (마침 제 Azure 계정도 무료 사용량을 다 써버려가지구요...ㅎ)

**Comment by jongfeel** [comment]
나중에 다시 GCP로 옮기는 작전도 괜찮은 것 같습니다.

어쨌든 추천드리는 작전은 하나의 cloud를 사용해서 통합 관리해야 나중에 귀찮지 않다 입니다.

**Comment by jongfeel** [comment]
그리고 작년 기준으로 한이음에서는 GCP에 대한 지원은 없었습니다.

Azure, AWS, IBM, KT 이 네개 였습니다. KT는 AWS기반이었으니 사실상 세개나 마찬가지었죠.

올해 지원을 해줄지는 모르겠지만 불확실성에 기대하는 것 보다 확실한 걸로 방향을 정해서 지원을 받는게 좋지 않을까 생각합니다.

제가 GCP도 괜찮다고 했을 때는 한이음 지원을 생각 안하고 얘기한건데, 지금은 조금 고려해 봐야할 문제이기는 하네요.

그리고 혼자 결정하기 어렵다면 팀원들과 논의해도 좋을 것 같습니다.

@kiJiyeon , @dkfma4915 님도 어떻게 결정하면 좋을지 얘기해 주시면 좋을 것 같아요.

**Comment by fora22** [comment]
https://github.com/JEoN-Ha/Senior-Project/issues/70#issuecomment-760019107

오늘 마침 Offline 미팅이어서 논의 했습니다 ㅎㅎ

> ### 논의 결과
>멘토님 의견에도 서로 다른 플랫폼에서 서비스를 구현하면 나중에 생각치 못한 문제로 돌아올 수 있고 # 한이음에서 GCP 지원도 불확실하니 **Azure로 결정**
> - 한이음 문의 결과 실습장비 담당자가 현재 바뀌어서 2021년도꺼는 새로 물어봐야 한다고 함. 이메일(hanium@fkii.org)로 연락을 달라고 했으니 일단 물어보도록 진행.

**Comment by jongfeel** [comment]
나중에 생각치 못한 문제

=> 97.2657% 확률로 관리, 문서화 문제입니다. 그리고 서비스 구현상의 복잡도도 영향을 미치겠죠.
