### ISSUE TITLE
10th review meeting

### ISSUE THREAD

**Issue by dkfma4915** [JEoN-Ha/Senior-Project#80]
# Meeting Rule
- 회의가 끝나면 다음 Review Meeting Issue 를 올린다.
- 회의(의견을 묻거나, ~해줬으면 or ~했으면 좋겠다 싶은 거, 진행에 있는 결정 사항 의논 등) 내용이 생길 때마다 Issue에 올려서 대화한다.
  - 이 때 각 주제별로 새로 Issue를 올리고 Review Meeting Issue에 링크를 남긴다.
  - #을 쓰면 알아서 Issue와 PR에 대한 링크를 고를 수 있다.
  - 만약 Issue를 올릴 정도로 복잡하지 않을 것 같다면 Review Meeting Issue에 올린다.
- 회의 날짜까지 모든 Issue에 대하여 결론이 지어지면 해당 날짜의 회의는 없어진다.
- 만약 결론이 지어지지 않거나 Comment로 이야기를 나누기 어렵다는 생각이 들 경우 회의날짜에 회의를 진행한다.

# 10th review meeting
## With Mentor 6th (Online)
~2021/01/27~ 2021/02/17 수요일 오후 11시

**Comment by dkfma4915** [comment]
# To do list (Offline Meeting 01/25)
- [ ] 최윤호 교수님 미팅
    - 랜선 연결 가능한 곳에서 시연 가능한지
    - 이미지 처리 방법 설명
    - 음식 전달 방식 (컨베이어벨트 높낮이 조절)
- [ ] 모터 선정 스펙 결정
- [ ] 컨베이너 벨트 논의
- [ ] 아름's To do list 정하기

**Comment by kiJiyeon** [comment]
# After review meeting (Offline) - 2021.01.25(월)

## 오늘의 To-Do List

### 최윤호 교수님 미팅
### 방향성 정하기
 - 문헌조사
 - 이미지 처리
 - 음식 전달 방식
 - 사이즈

## 최윤호 교수님 면담 내용

### 1. 이미지 처리

Q. 현재 공개 되어있는 이미지 인식 API를 사용하여 진행해도 감점이 없을까요?

A. 공개 되어있는 것들을 직접 갖다 써도 좋다. (감점이 있어도 어쩔 수 없는거지만)일단은 완성을 시키는게 먼저이고, 나중에 시간이 남으면 직접 구현을 해도 좋을 것 같다.

### 2. 음식 전달 방식
- 음식 전달 방식에 굳이 컨베이어 벨트를 사용할 필요가 없다. 

- 만약에 컨베이어 벨트를 사용하면 이걸로 뭘할건지, 왜 이걸 썼는지 등 타당한 근거가 받쳐줘야함 -> `당위성`이 있어야함

- 따라서 문헌 조사를 해서 이 기술엔 어떤 문제점, 단점이 있는지를 파악을 하고 해결 방법을 찾아가며 당위성을 부여해야함
_당위성이 잘 되어있어야 컴팩트한 발표, 설명이 가능하고 흔들림 없이 방향성이 잘 갖추어져있는 프로젝트를 진행할 수 있음._


## 방향성 회의 내용
- 문헌조사 : 기존기술의 문제점과 해결방안을 찾아가며 프로젝트의 당위성을 부여해야함
- 이미지 처리 : 기능을 먼저 구현을 하고, 나중에 시간적 여유가 있을 경우 직접 알고리즘을 짜서 구현해보기
- 음식 전달 방식 : 벨트는 제외하고, 높낮이를 조절하여 전달하는 방식 (like 엘리베이터)
- 사이즈 : 우선, 게이트 바는 길지만 가벼운 재료를 이용해서 만들기로!

## 향후 계획

### 대원
    - `router` 코드 빠르게 작성
    - 문헌 조사(sub)
    
### 지연
    - `Swagger.yaml`문서 수정 & 도보이용자 추가
    - Web Deploy 후 동작 테스트
    - 문헌 조사(sub)
    
### 아름
    - 문헌 조사 (main)
    - front: 도보 이용자 추가
    - Jetson Nano: OS설치 및 카메라 연결 (+ 아두이노 제어)

**Comment by dkfma4915** [comment]
멘토님! 오늘 온라인 미팅은 다음으로 넘어가도 될 것 같아요 !ㅎㅎ
다음 온라인 미팅은 2월 3일 수요일 어떠신가요?? 
@jongfeel

**Comment by jongfeel** [comment]
제가 먼저 얘기하려고 했는데 잊고 있었네요

저에게 할당된 issue와 pull request가 없었으므로 자연스럽게 연기되는게 맞긴 합니다.

그러면 2월 3일로 변경 할께요.

**Comment by dkfma4915** [comment]
> 그러면 2월 3일로 변경 할께요.

네 알겠습니다 ㅎㅎ

**Comment by kiJiyeon** [comment]
넵!! 확인했습니다!!

**Comment by fora22** [comment]
네~ 확인했습니다~

**Comment by jongfeel** [comment]
오늘까지 저하고 얘기할 만한 내용은 #85 이거 하나 정도였는데요.
이 내용도 미팅해서 얘기해도 15분을 넘지 않을 것 같아서 오늘 진행할지 다음으로 미룰지 결정을 해야 할 것 같습니다.

**Comment by dkfma4915** [comment]
> 오늘까지 저하고 얘기할 만한 내용은 #85 이거 하나 정도였는데요.
> 이 내용도 미팅해서 얘기해도 15분을 넘지 않을 것 같아서 오늘 진행할지 다음으로 미룰지 결정을 해야 할 것 같습니다.

제 생각은엔 해결된 내용이니 다음으로 미뤄도 괜찮을것 같습니다!

**Comment by fora22** [comment]
> 제 생각엔 해결된 내용이니 다음으로 미뤄도 괜찮을것 같습니다!

제 생각도 동일합니다!

**Comment by jongfeel** [comment]
그러면 다음 주 수요일 (2월 10일)로 미뤄 놓겠습니다.
일정 조절이 필요하시면 미리 얘기해 주세요.

**Comment by kiJiyeon** [comment]
넵 확인했습니다~

**Comment by fora22** [comment]
# After review meeting (Offline) - 2021.02.01(월)

- [ ] 3A 어댑터 찾기
- [ ] 미래화방 방문

## 어댑터
- Jetson Nano에서 Ubuntu 를 깔아 아두이노를 제어를 진행중 -> 아름
- 허나 Jetson에서 모니터, 웹캠을 연결하면 전원이 셧다운 되는 일이 발생함
- 어댑터의 출력 전원이 부족한 것으로 예상되어서 3A 이상의 어댑터를 찾기로 함
- **찾아서 조치하였음!**

## 미래화방 방문
하드웨어 시뮬레이션을 위한 재료를 구매하기 위해 미래화방(수원)
- 방문 차량 안전바
- 매장
- 음식 전달 벨트(?)

위 3가지를 구현 예정

방문 차량 안전바만 구현하기 위해 소량의 아크릴판(?)과 붙일 수 있는 본드를 구매함

이후에 필요한 것은 2월 16일 이후 캡스톤 디자인 지원금을 통해 구매 예정
- 글라인더(소형)
- 추가 아크릴판(?)

@kiJiyeon @dkfma4915 확인 바람~

**Comment by fora22** [comment]
# After review meeting (Offline) - 2021.02.08(월)

- [ ] 서보 모터 교체
- [ ] 현재 진행상황 공유

## 서보 모터 교체
현재 아름이 사용하고 있는 서보 모터는 360도 회전(무한 회전)이 가능함(비싼 모터임)

이 모터는 0도 기준점을 나사로 조여 맞춰줘야하는 조건이 있는데, 문제는 이 나사가 시간이 지나면 풀려서 0도 기준점이 시간에 따라 달라지는 문제점이 있음
 
따라서 일반적인 양방향이지만 무한 회전은 아닌 모터로 교체하기로 함

## 현재 진행상황 공유
- 키보드 버튼을 통해 카메라가 이미지를 로컬 폴더에 저장하도록 구현 완료
  - 초음파 혹은 적외선 센서를 통해 일정 거리 이하이면 저장되도록 기능 추가를 부탁함
- Web Deploy 중 서버와 연결하지 못했다는 에러가 떠서 해결 중
  - 아마 router & fetch code의 URL 문제
  - 혹은 서버 쪽 동시 실행이 되지 않는 문제일 것으로 예상됨
- router code는 중간중간 수정할 것이 계속 나오지만 수욜(2/10)까지 완료될 것으로 보임

@kiJiyeon @dkfma4915 확인 바람~

**Comment by jongfeel** [comment]
오늘 온라인 미팅이 예정되어 있는데요

저와 논의할 issue, pull request가 없습니다.
계속해서 web쪽에 개발 중인 문제를 해결 하는 과정인 것 같은데,
같이 리뷰할 필요가 있으면 pull request를 만들어 주세요.

오늘 미팅은 다음주로 미뤄 놓겠습니다.

**Comment by kiJiyeon** [comment]
넵! 확인했습니다

**Comment by dkfma4915** [comment]
> 오늘 미팅은 다음주로 미뤄 놓겠습니다.
네 알겠습니다!

**Comment by fora22** [comment]
넵 확인했습니다~

**Comment by jongfeel** [comment]
오늘 온라인 미팅은 진행하는 걸로 해보겠습니다.

이번 pull request가 하나 있고 코멘트를 달아 뒀기 때문이죠.
30분 정도면 얘기할 수 있을 것 같습니다.

**Comment by fora22** [comment]
> 오늘 온라인 미팅은 진행하는 걸로 해보겠습니다.
> 
> 이번 pull request가 하나 있고 코멘트를 달아 뒀기 때문이죠.
> 30분 정도면 얘기할 수 있을 것 같습니다.

확인했습니다. 마침 고민하고 있던 문제가 있는데 회의 때 이야기하면 좋을 것 같습니다!!
# 멘티들이 결정할 수 있는 Issue
- Issue 정리
- 졸업작품 교수님께 당위성을 위한 문헌내용 보내기
- 
# 멘토님과 같이 의논해볼 Issue
- OrderNo를 어떻게 처리할지 -> OrderNo는 Auto 로 들어가는데 Insert의 기준이 애매모호함
  - 부연설명: 사용자 A는 1번 주문한 경험이 있다(OrderNo가 1). 새로 주문하려고 한다면 ordertable에 새로운 OrderNo(2번) Insert를 할 것이다. 이를 장바구니에 담는다고 가정하자. 하지만 생각이 바뀌어 장바구니를 모두 비었다. 다음 날, 장바구니에 새로 담았다면 이전 OrderNo(2번)을 기억해 놓았다가 유지할 것인지, 아니면 새로운 OrderNo(3번)을 부여할 것인지? 기억한다면 어디서 기억할 것인지? (DB? Front)

**Comment by jongfeel** [comment]
장바구니 떄문에 고민인 프로세스를 하나 더 추가해 보면 좋을 것 같습니다.

- 장바구니 테이블 추가: 사용자 id, 메뉴 id의 컬럼
- 서버도 장바구니 추가/삭제 API
