### ISSUE TITLE
[Untact Drive-Thru] 문헌조사

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#83]
조사한거 공유하자@

**Comment by kiJiyeon** [comment]
# 1. 교통 방해 문제  

## "차량 통행 방해" 문제 51.4% 
국민권익위원회(위원장 전현희, 이하 국민권익위)가 최근 6년(2015.1.∼2020.7.)간 민원분석시스템에 수집된 승차 구매점 관련 민원을 분석한 결과, 총 1,121건으로 매년 평균 51.5%씩 증가한 것으로 나타났다.

```
< 승차 구매점 관련 민원 사례 >

# 승차 구매점에서는 차량이 쉴 새 없이 들어가고 나오기 때문에 보행자는 차량 통행이 잠시 쉬는 틈을 기다렸다가 차 사이로 지나다녀야 합니다. (2020.6.14.)

# 사거리에서 녹색 신호가 켜지면 직진 차량과 OO 승차 구매점에서 나오는 차량들이 뒤엉켜서 직진하려는 차는 불과 몇 미터도 이동하지 못합니다. 특히 토요일이나 휴일에는 너무 많은 스트레스를 받습니다. (2019.10.19.)

# 매장 앞 인도 겸 진출입로에서 비상 점멸등이나 방향지시등도 켜지 않은 채로, 보행자가 있는데도 그대로 진입하는 차량을 신고합니다. (2019.5.15.)

# OO 승차 구매점으로 들어가려는 차량 대기줄인 것을 알지 못하는 뒤쪽 운전자들은 영문도 모른 채 따라 늘어서 있습니다. 결국 매장 이용 차와 지나가던 차가 뒤엉켜 차량 줄은 몇 배로 길어집니다. (2019.2.5.)


출처: 국민권익위원회
```

앞서 국민권익위는 정책참여 플랫폼 ‘국민생각함’에서 ‘승차 구매점의 문제점과 개선방안’에 대해 국민 의견수렴을 실시하였고, 총 336명이 참여한 설문조사에서 이번 민원분석 결과와 동일하게 ‘차량 통행 방해’ (45.1%)를 승차 구매점의 가장 큰 문제로 인식하는 것으로 나타났다.

응답자의 89.8%는 혼잡지역 등에는 승차 구매점 입지 제한이 필요하다는 의견을 제시했으며, 교통정체 문제에 대한 책임 부담 주체는 승차 구매점이라는 의견이 다수였다(65.1%). 또 이런 문제를 해소하기 위해 교통영향평가 등 입지 제한 규정을 마련해야 한다(37.8%)고 응답했다.

-> 해결방안 : `커넥티드 카 커머스` 

>**커넥티드 카 커머스**란?

>자동차와 신용카드 번호간 연계되는 디지털 아이디를 이용하여 결제하는 서비스 
운전자가 드라이브 스루를 이용할 때 방문전 주문과 결제를 마친 후 상품 수령만 매장에서 할 수 있게 되는것
-> 주문/결제시 차가 정체되어 일어날 수 있는 사고를 예방 가능

# 2. 비대면 서비스의 이유

## 비말,에어로졸에 의한 바이러스 확산 (전국적으로도 그런지 확인이 필요하지만)

코로나 19로 인해 드라이브 스루 이용이 증가하고 있지만, 자가용은 '개인공간'으로 구분되기 때문에 드라이브 스루 이용자는 방역망에서 벗어나 있다.
대구의 한 드라이브스루 매장 이용자들을 관찰한 결과, 5분간 방문한 10명의 이용자들 중 1명이 마스크를 착용하지 않은 상태로 음료를 사갔다. 또한 10분간 다른 드라이브 스루 매장을 방문한 차 10대중 2대의 동승자들은 마지막까지 마스크를 착용하지 않았다.

통상 드라이브 스루 이용자는 결제창구와 1~2m 정도로 가까운 거리에 정차하고, 결제 과정에 점원과 간단한 대화를 나눠야 해 바이러스 전파 위험이 있지만 마스크를 쓰지 않아도 제재할 방법이 없다. 매장 안에 들어가는 것은 아니기 때문에 다중이용시설 이용 시 지켜야 하는 거리두기 지침이 적용되지 않기 때문이다.

드라이브 스루 고객을 상대하는 점원들은 불안감을 호소한다. 차창 가까운 곳의 외부인은 차 안에서 흘러나온 공기에 노출되기 때문에 동승자로 인한 비말·에어로졸 확산에 의한 감염 가능성도 배제할 수 없다는 지적도 나온다.

패스트푸드점 아르바이트생 정모(여·22)씨는 “마스크를 써 달라고 했을 때 ‘내 차 안인데 왜 써야 하느냐’면서 되레 따지는 사람도 있었다”면서 “결제 전에 추가 주문이나 메뉴 선택 때문에 일행끼리 말을 많이 한다. 일행 간 대화여도 비말은 차 밖까지 튈 수 있는데 무증상자가 있을지도 모르니 걱정이 된다”고 하소연했다.


## 안타까운 시민의식(이건뭐,,, 일단 적어봄)

- 쓰레기 버려달라고함
- 고성 및 욕설을 내뱉는 경우도 있음
- 음식 던지고 튐

**Comment by dkfma4915** [comment]
# 드라이브 스루의 문제점
- 스피커폰의 고객과 직원 사이 불명확한 의사소통
  - 주변의 소음이나 좋지 못한 음질
- 외국인, 청각장애인 또는 언어장애인과의 의사소통 불가
  - 외국인 : 영어 메뉴판을 직원이 직접 보여주거나 간단한 영어 사용
  - 장애인 : 글로 써서 보여줌
- 고객이 주문 후 기다리는 시간이 지루함
- 드라이브 스루 이용 전 '미리 보는 메뉴'에는 모든 메뉴의 정보가 없기 때문에 무용지물
- 메뉴 보드에는 제품의 이름과 가격이외의 다른 정보가 없음
  
# Untact Drive-Thru의 장점
- '주문하는 곳'에 배치된 인력 감소 가능 (인력손실과 인건비 감소)
- 스피커폰의 문제점 해결 가능
- 외국인 또는 언어장애인도 불편함 없이 주문 가능
- 메뉴를 한눈에 볼 수 있어 빠르게 선택 가능
- 주문한 제품의 총 가격을 미리 빠르게 알 수 있어 계산의 오류나 착오 방지

# Drive-Thru 동향
- 코로나19로 인해 유통업계에서 가장 '핫'한 소비 패턴
- 카페나 패스트푸드 업체 뿐만 아니라 재래시장, 편의점, 대형마트, 백화점, 호텔 등 유통업계 전반으로 확대
- 드라이브스루 매장 매출 급증
  - 맥도날드 : 1분기 드라이브스루 이용 차량 1천만대를 넘었고 3월 매출 전년 동기 대비 30% 증가, 올해 상반기에는 2천만대 이상의 차량, 전체 매출은 지난해 대비 30% 이상 증가
  - 스타벅스 : 드라이브스루 주문 건수는 1~4월 작년 같은 기간 대비 40% 증가
  
# 당위성을 높이기 위해 추가해야 할 부분
- 메뉴이름, 가격 이외의 정보를 포함
  - 영양, 재료 등

# 쉑쉑버거의 드라이브 스루


# 참고사진
![image](https://user-images.githubusercontent.com/52308823/105830003-552dc580-6008-11eb-85cf-1755deca4ad4.png)

# 참고자료
[드라이브 스루(Drive-Thru)를 위한 멀티미디어 메뉴 시스템 제안](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001557078)
[수산시장부터 백화점·호텔까지... 코로나19에 대세된 ‘드라이브스루’](https://www.vop.co.kr/A00001513890.html)
[드라이브 스루의 미래](https://brunch.co.kr/@eddle/79)

**Comment by dkfma4915** [comment]
# 정리
- 드라이브 스루의 문제점 -> 언택트 드라이브 스루로 해결 (이것이 곧 Untact Drive-Thru의 장점)
- 특히 `메뉴 보드에는 제품의 이름과 가격이외의 다른 정보가 없음`이 부분은 우리가 `메뉴이름, 가격 이외의 정보를 포함`을 추가한다면 당위성을 더 높일 수 있다! 
- Drive-Thru 동향은 그냥 Readme 앞부분에 추가해놓으면 좋을듯!
- 밑에 참고사진 2개는 필요 없음!

**Comment by kiJiyeon** [comment]
# 정리

## 1. `커넥디트 카 커머스`를 이용하면 교통 방해 문제를 해결(개선)할 수 있다.

### 근거
 

> 국민권익위는 정책참여 플랫폼 ‘국민생각함’에서 ‘승차 구매점의 문제점과 개선방안’에 대해 국민 의견수렴을 실시하였고, 총 336명이 참여한 설문조사에서 이번 민원분석 결과와 동일하게 ‘차량 통행 방해’ (45.1%)를 승차 구매점의 가장 큰 문제로 인식하는 것으로 나타났다.


-> 앱/웹을 이용하여 미리 주문을 하기 때문에, 차량이 금방금방 나가기 때문에 차량 줄이 길게 늘어지는 것을 막을 수 있음


## 2. 비대면 서비스를 제공함으로써 비말, 에어로졸에 의한 바이러스 확산을 막을 수 있다.

### 근거

>  대구의 한 드라이브스루 매장 이용자들을 관찰한 결과, 5분간 방문한 10명의 이용자들 중 1명이 마스크를 착용하지 않은 상태로 음료를 사갔다. 또한 10분간 다른 드라이브 스루 매장을 방문한 차 10대중 2대의 동승자들은 마지막까지 마스크를 착용하지 않았다.

> 통상 드라이브 스루 이용자는 결제창구와 1~2m 정도로 가까운 거리에 정차하고, 결제 과정에 점원과 간단한 대화를 나눠야 해 바이러스 전파 위험이 있지만 마스크를 쓰지 않아도 제재할 방법이 없다. 매장 안에 들어가는 것은 아니기 때문에 다중이용시설 이용 시 지켜야 하는 거리두기 지침이 적용되지 않기 때문이다.


-> 기존의 드라이브 스루 이용시, 결제 또는 제품을 수령할 때 직원과 대면접촉을 하게 된다. 이 때 차안의 에어로졸 또는 이용자의 비말에 의해 바이러스가 확산 될 가능성이 있다. 또한, 만약 이용자가 마스크를 착용하지 않았을 경우에도 제재할 방법이 없다.

(직원이 마스크를 착용했다하더라도, 이용자가 마스크를 쓰지 않으면 확산 위험이 더 큼)

**Comment by kiJiyeon** [comment]
근데 우리 컨베이어 벨트를 사용하는거에 관한 당위성은 어케 찾지??

**Comment by dkfma4915** [comment]
> 근데 우리 컨베이어 벨트를 사용하는거에 관한 당위성은 어케 찾지??

아 그거에 대한거 못찾긴했는데 다시 한번 찾아보고 더 추가하도록 하겠슴당
그리고 생각했던건 우리 설문조사에서 드라이브스루 이용시 감염에 대한 걱정을 하냐는 질문 있었자나 그걸로 근거를 들고 접촉이 발생하지 않도록 음식 전달을 해야했고, 가장 간단한(?) 컨베이어벨트를 사용했다! 라고 말하는걸로 생각했었엉 내가 한말이 이해가 되려나,,,,

**Comment by kiJiyeon** [comment]
> 아 그거에 대한거 못찾긴했는데 다시 한번 찾아보고 더 추가하도록 하겠슴당
나도 찾아볼게!!!!!!!!!!!!!!
> 그리고 생각했던건 우리 설문조사에서 드라이브스루 이용시 감염에 대한 걱정을 하냐는 질문 있었자나 그걸로 근거를 들고 접촉이 발생하지 않도록 음식 전달을 해야했고, 가장 간단한(?) 컨베이어벨트를 사용했다! 라고 말하는걸로 생각했었엉 내가 한말이 이해가 되려나,,,,
이해는 감!!!! 그럼 그거랑 다른 전달방식들(관절형 로봇팔 등등)의 문제점을 들어서 컨베이어 벨트로 했다~ 라고 하면 되겠지..?

**Comment by kiJiyeon** [comment]
> > 아 그거에 대한거 못찾긴했는데 다시 한번 찾아보고 더 추가하도록 하겠슴당
> > 나도 찾아볼게!!!!!!!!!!!!!!
> > 그리고 생각했던건 우리 설문조사에서 드라이브스루 이용시 감염에 대한 걱정을 하냐는 질문 있었자나 그걸로 근거를 들고 접촉이 발생하지 않도록 음식 전달을 해야했고, 가장 간단한(?) 컨베이어벨트를 사용했다! 라고 말하는걸로 생각했었엉 내가 한말이 이해가 되려나,,,,
> > 이해는 감!!!! 그럼 그거랑 다른 전달방식들(관절형 로봇팔 등등)의 문제점을 들어서 컨베이어 벨트로 했다~ 라고 하면 되겠지..?

**Comment by dkfma4915** [comment]
> 이해는 감!!!! 그럼 그거랑 다른 전달방식들(관절형 로봇팔 등등)의 문제점을 들어서 컨베이어 벨트로 했다~ 라고 하면 되겠지..?

그러면 될거같아!

**Comment by fora22** [comment]
@kiJiyeon  정리하다 느낀건데 `비말,에어로졸에 의한 바이러스 확산 (전국적으로도 그런지 확인이 필요하지만)`에 대한 출처를 남겨줬으면 좋겠음!!

**Comment by kiJiyeon** [comment]
> @kiJiyeon 정리하다 느낀건데 `비말,에어로졸에 의한 바이러스 확산 (전국적으로도 그런지 확인이 필요하지만)`에 대한 출처를 남겨줬으면 좋겠음!!

[비말,에어로졸에 의한 바이러스 확산 출처](https://www.idaegu.co.kr/news/articleView.html?idxno=331415)

**Comment by dkfma4915** [comment]
## 스타벅스 My DT pass
- 스타벅스에서 우리가 생각한 차량번호 등록을 이미 하고 있었음..
- 요즘 스타벅스를 많이 가서 사이렌오더 써보려고 앱 깔았는데 차량번호 등록이 있는겨..!
- 결제수단까지 등록해두고 앱으로 미리 결제 다하고 DT가서 차량번호 인식 후 바로 음료 주는 방식임
![image](https://user-images.githubusercontent.com/52308823/109265865-8f2df980-784a-11eb-8593-c2f0910e138a.png)
![image](https://user-images.githubusercontent.com/52308823/109265879-948b4400-784a-11eb-9b70-eec056d72be0.png)

**Comment by fora22** [comment]
> ## 스타벅스 My DT pass

어우...젠장....서비스 업종을 바꿔야 하나 택배같은 걸루..

**Comment by dkfma4915** [comment]
> > ## 스타벅스 My DT pass
> 
> 어우...젠장....서비스 업종을 바꿔야 하나 택배같은 걸루..

근데 우리는 음료 전달까지 언택트로 한다는 거고
서비스 업종도 햄버거, 음료 등 DT 가능한 서비스들한테 적용시킬 수 있다! 이니까 조금 다르지않을까?

**Comment by fora22** [comment]
다르긴 한건 맞는거같아. 하지만 스타벅스는 약점이 될 수 있으니 `음식메뉴` 나 건물 모양(?)이 스타벅스랑 카페가 연상되지 않도록, 잘 꾸며야 할듯?!
