### ISSUE TITLE
Ubuntu 로그인 실패 현상

### ISSUE THREAD

**Issue by dkfma4915** [JEoN-Ha/Senior-Project#84]
Jetson nano에 ubuntu 설치 완료하고 로그인을 하려는데
`sorry that didn't work please try again` 이라는 문구가 뜨는 현상이 발생함
![image](https://user-images.githubusercontent.com/52308823/106251772-bd72e600-6258-11eb-91a1-46f4f0d65030.png)

분명 비밀번호는 맞게 입력했는데 몇번을 입력해도 똑같은 문구가 뜸
혹시 이런 경우를 본적 있어......?
구글링도 해봤는데 아직 딱히 해결방법을 못찾음.. ㅠㅠ

이런 경우를 본적이 없다면 일단 혼자 해보겠음!!!

**Comment by fora22** [comment]
단순한 비밀번호 오류일 가능성이 높을거같은데.. 정 안되면 sd카드 포맷하고 다시 녹여서 부팅해보는것을 추천함!

**Comment by dkfma4915** [comment]
다시해서 됐음!!!!
