### ISSUE TITLE
opencv 코드에 외부 회로 연결 방법

### ISSUE THREAD

**Issue by dkfma4915** [JEoN-Ha/Senior-Project#86]
지금 하려는게 초음파센서로 거리측정해서 얼마 이하이면 사진 캡쳐하려거잖아
근데 opencv 코드에 시리얼 통신 코드를 추가해서 아두이노랑 시리얼통신을 하는게 맞는건가?
예제가 몇개 안나오길래 내가 잘못생각하고 있는건가해서!!

**Comment by fora22** [comment]
그렇지! 다른 방법도 있는데 그걸로 하는게 바람직할 것 같아

예제가 잘 안나오면 키워드를 밑에꺼를 참고해서 변경하길 바람
- 라즈베리파이 
- 아두이노 시리얼 통신
- 라즈베리파이로 아도이노 제어
- Ubuntu 에서 아두이노 제어
