### ISSUE TITLE
우리 집을 지어봐야 되지 않을까?!

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#93]
수강신청이 지났으니 우리가 금액적으로 지원 받을 수 있을텐데 2월안에는 집을 지어놔야 그래도 합칠때 바로 합칠 수 있지 않을까 싶은데!!

동의한다면 금액 지원에 관해서 문의할 사람이랑 만드는 날짜를 정했으면 좋겠음!

**Comment by dkfma4915** [comment]
문의는 사다리타기 고!
만드는 날짜는 목요일 2시이후, 금요일 저녁전까지 가능!

**Comment by fora22** [comment]
본인은 수요일 빼고 다 가능할듯

사다리 타기는 지연이가 확인하면 카톡에서 하겠음!

**Comment by kiJiyeon** [comment]
나는 이번주라면 수요일에만 가능!! 사다리 타기 고고

**Comment by fora22** [comment]
> 나는 이번주라면 수요일에만 가능!! 사다리 타기 고고

그럼 이번주는 불가능이네?

**Comment by dkfma4915** [comment]
그럼 담주 월요일 3월 1일..?

**Comment by kiJiyeon** [comment]
나는 3월1일 가능이용~

**Comment by fora22** [comment]
> 그럼 담주 월요일 3월 1일..?
> (아 그리고 내가 요새 정신이 없어.. 엄마 병원때문에.. 미안 ㅜㅜ 자세한 얘기는 나중에 기회되면 할게,, 오늘도 빅사건이 있었어서,,)

아 지금 봤넹 괜찮아용 ㅎㅎ

근데 3월 2일은 어때? 1일은 공휴일이라 피하고 싶어!! @kiJiyeon @dkfma4915

**Comment by dkfma4915** [comment]
상관없는데 그날 오전 양성평등강의가 실강일지 아닐지 몰라서 시간은 딱 못정하겠는디 ㅠ 전공설은 녹강이겠지..?

**Comment by kiJiyeon** [comment]
나도 아름이랑 시간표 똑같아서 3월2일은 잘 모르겠다!! 일단 3월3일 오전에는 수업 없어서 가능!

**Comment by dkfma4915** [comment]
> 나도 아름이랑 시간표 똑같아서 3월2일은 잘 모르겠다!! 일단 3월3일 오전에는 수업 없어서 가능!

나도 3월3일 오전 수업없고 오후 디통은 녹ㄱ강 이미 lms에 올라오는걸 보니 녹강이므로 수욜 상관없슴!

**Comment by kiJiyeon** [comment]
> 나도 3월3일 오전 수업없고 오후 디통은 녹강 이미 lms에 올라오는걸 보니 녹강이므로 수욜 상관없슴!
그러네 나도 수요일은 아예 될것같다!! 대원쿤은?

**Comment by fora22** [comment]
그럼 3일(수) 오전 10시 반에 보는걸루!
