### ISSUE TITLE
컨셉 비교를 위한 자료조사에 대하여

### ISSUE THREAD

**Issue by fora22** [JEoN-Ha/Senior-Project#94]
## 기존 컨셉
- 음식점
  - 카페
  - 패스트 푸드점
## 비교 컨셉
- Main 은 대형마트
  - 이마트 트레이더스
  - 쿠팡
  - 이마트 등
- Sub 는 유통 업계

컨셉 비교를 위해 자료조사를 하고 정리하여 Issue 에 올려주길 바람

**Comment by kiJiyeon** [comment]
### 아직 정리전임!

https://blog.naver.com/inkyu118/221801425988 근데 우리가 생각한거랑 똑같은거 있어서 가져와봄

**Comment by dkfma4915** [comment]
## 드라이브 스루 농산물 및 상품 판매 예시
### 코로나19 감염 방지를 위해 '드라이브 스루'형태로 진행해 시민과의 접촉을 최소화
- 전북도청과 전북농협이 공동으로 추진한 '코로나19 극복, 축산물 드라이브 스루 할인판매 행사’가 2시간만에 완판되는 성과를 보임
- 고양국제꽃박람회의 플라워 마켓
- 농식품부-aT, 드라이브 스루 지원 확대

## 롯데백화점'드라이브 픽'
- 롯데백화점 앱을 이용해 구매 후 결제 시 상품 수령 시간을 설정하면 점포의 발렛파킹 라운지에서 차량에 탄 채 상품을 받을 수 있음 (울산, 광주점에서만)
- 현재 전국 롯데백화점은 온라인 or 모바일로 구매한 상품을 매장에서 받는 '스마트픽' 운영중 -> 비대면으로 강화한 것이 드라이브 픽
[드라이브 픽](https://biz.chosun.com/site/data/html_dir/2020/03/18/2020031804766.html)

## 이마트 '픽업서비스'
- 서수원점과 성수점에서 시작
- SSG닷컴 앱으로 상품 주문 후 서수원점 지상 4층 야외주차장에 마련된 픽업서비스 수령장소에서 마트 직원이 구매물품을 차에 실어줌

## SSG닷컴의 '익스프레쓱'
- 신선식품이 아닌 패션잡화 픽업서비스
- 단순 매장 픽업X
- 피팅룸, 수선, 교환 서비스를 제공해 차별화함

## 편의점 CU 드라이브 스루 시범 서비스
- 전용 앱 '오윈'을 통해 상품을 고른 뒤 점포를 방문해 수령
- 상품을 결제하면 앱 자체에서 점포까지 길 안내 서비스 제공
- 도착 후 '점원 호출'버튼을 누르면 근무자가 차량으로 물건 전달
[신세계, CU 참고기사](http://www.kyeonggi.com/news/articleView.html?idxno=2337341)

## 하지만 식료품 매장픽업 서비스 이용률 저조
- 이마트 픽업 서비스 운영을 2월 중순부터 잠정 중단
- 롯데백화점 '드라이브 픽'도 잠정 중단
    - 이유
      1. 코로나19 확산세가 주춤하자 이용건수 급감
      2. 우리나라 대형마트는 대도시 중에서도 교통 중심지에 주로 입지하고 있어 픽업 서비스가 발달하기 힘든 형태, 픽업서비스가 활성화될수록 교통 혼잡이 심화될 가능성 높음 -> 물류 효율이 떨어짐
      3. 대중교통을 이용하는 소비자도 많아 매장픽업 서비스보다 문앞 배송을 더 선호하는 특성이 있음 -> 쿠팡, 마켓컬리, SSG닷컴이 발달한 이유 

## 패션잡화 픽업서비스는 오히려 급증
- 신세계 '익스프레쓱' 이용률 증가 (지난해 12월 오픈 첫주 대비 40% 증가)
- 롯데백화점의 '스마트 픽' 서비스 10-11월 매출 전년 대비 44% 증가
- 패션잡화의 경우 예약 후 한달씩 기다려서 사는 등 계획된 소비를 하는 경우가 많기 때문
[픽업 서비스 한국에서 안통하는 이유](https://www.ajunews.com/view/20210203143338751)

## 결론
- 아직.. 생각중

**Comment by fora22** [comment]
# 대형마트의 사례
![image](https://user-images.githubusercontent.com/48875566/110205878-f177a180-7ebd-11eb-9e90-0a2a4f1c5d47.png)

- 기본적인 드라이브 스루 방식과 같음
- 물건을 미리 주문(모바일, 온라인)하고 매장에 가서 받음
- 주문한 물건은 점원이 건네줌
- 하나의 사례 [기사 참조](https://www.hankookilbo.com/News/Read/201702011530899819)
  - 명절을 앞두고 차례상에 올릴 음식 마련을 위해 미리 주문한 뒤
  - 퇴근길에 집 근처 롯데마트 중계점에서 주문한 물건들 픽업
  - "**직장을 직장을 다니는 주부들은 밤 늦게 따로 시간을 내 장보기가 만만찮고**, **원하는 시간에 배송기사로부터 물건을 전달 받기도 어렵다**"며 “마트가 드라이브스루 매장의 장점을 접목한 덕분에 배송비 부담 없이 필요할 때마다 물품을 소량 구매할 수 있어 정말 편하다”
  - 하지만 반대의 사례로 **아름이의 자료**도 있음
    - 식료품은 이용률 저조
    - 하지만 패션 잡화 픽업 서비스는 급증

# 새로운 아이디어
## 드라이브 스루 - 고속도로 휴게소
### 배경
- 윗 기사와 [같은 기사](https://www.hankookilbo.com/News/Read/201702011530899819) 사례
- '투썸 플레이스'에서 서울에서 김포를 통해 강화로 이어지는 48번 국도와 맞닿아 있는 곳에 드라이브 스루 매장 설치
- **통행차량의 방문이 용이**해서 이용 고객이 많음
- "각종 사무실이 있는 오피스 상권이라 차를 이용해서 오가는 고객들이 많아 DT매장을 테스트베드로 만들었다"

### 제안 내용
- 통행차량의 방문이 용이하다면 고속도로 휴게소에서도 비대면 서비스를 제안하는 것도 괜찮지 않을까 싶은 생각이 듬
- 비대면 플랫폼 제안 내용
  1. 홈페이지를 통해 고속도로 선택
  2. 고속도로 휴게소 선택
  3. 물품 선택
  4. 개발 내용대로 픽업

## 사전 조사
- 실제로 2022년까지 휴게소 7곳으로 드라이브 스루 모델을 적용 예정
- 휴게소 대기시간을 단축시키기위해 모바일 서비스도 제공 예정
- **비대면에 관해서는 특별한 내용은 없고, 기존 드라이브 스루 모델을 사용할 것으로 보임**
- 휴게소에서 사용되고 있는 드라이브 스루 서비스는 현재 작은 부스를 통해 운영하고 있음 - [기사 1](https://www.asiae.co.kr/article/2020042815171814492), [기사 2](https://www.kyongbuk.co.kr/news/articleView.html?idxno=2038231)
  ![image](https://user-images.githubusercontent.com/48875566/110206382-9abf9700-7ec0-11eb-831f-383616b451dd.png)
  ![image](https://user-images.githubusercontent.com/48875566/110206404-c5115480-7ec0-11eb-95a2-363de71bd2cd.png)
___ 
# 다른 이야기 - 우리가 왜 드라이브 스루 모델을 개발하는지에 대해
2020년에 관광학 논문: `포스트 코로나에 대응하는 정부의 혁신적인 관광정책 연구`에 따르면 드라이브 스루 모델 개발에 대한 내용이 있음

또한 우리에게 당위성을 실어줄 좋은 내용이 많아보임

## 1. 서론과 이론적 배경을 통한 코로나 19의 관광산업 파급효과
- 서론과 이론적 배경에서 코로나 19가 끼친 관광산업 영향에 대해 기술하고 있음
- 간단히 정리하자면 다음과 같음 
  - 경제적으로 매우 힘들어졌고
  - 다른 산업은 재택근무가 장려되지만 관광산업은 재택근무를 할 수 없음
  - 즉, 위기 상황(감염병 등)에 대응하여 관광 산업 관련 메뉴얼, 혁신적인 관광정책이 필요하다고 촉구
- 포스트 코로나(Post COVID-19) 대응 혁신적인 관광정책
  - 여기서 **드라이브 스루 관광 모델을 개발해야 한다**는 내용이 나옴
- 이는 드라이브 스루 모델을 개발하게 되는 당위성으로 추가하면 좋겠다는 생각이 듬
### Reference
이웅규, 구정대. "포스트 코로나에 대응하는 정부의 혁신적인 관광정책 연구". 관광학연구, vol. 44, pp.87-106, 2020.

Lee Woong-kyu, Goo Jung-dae. "Government's Innovative Tourism Policy Research in Response to Post-COVID-19". Journal of Tourism Sciences, vol. 44, pp.87-106, 2020.
___
# 결론
- 대형마트 혹은 유통에서는 기존 드라이브 스루 모델을 적용, 개발해 나가고 있음
- 그러나 아직 **점원간의 비말접촉에 대한 문제점 인식 및 해결점은 아직 없는 것으로 판단됨**
- 고속도로 휴게소에는 아직 드라이브 스루 모델이 적용되지 않았지만 곧 적용될 예정(2022년 7개 휴게소 적용 예정)
## 사견(개인적인 의견)
- 아이디어 제안 방향을 2가지로 나눌 수 있다고 생각함
  1. 좁은 범위의 언택트 드라이브 스루 모델
  2. 넓은 범위의 언택트 드라이브 스루 모델

### 좁은 범위의 언택트 드라이브 스루
- 대형마트, 카페, 패스트 푸드, 고속도로 등과 같이 하나의 산업 혹은 서비스를 특정해서 디테일하게 구현
- 장점 : 디테일하게 구현하기 때문에 바로 서비스에 적용할 수 있다고 어필 가능
- 단점 : '굳이..?'라는 생각이 들 수 있음 / 설치 비용이나 여러가지 측면에서 경제성이 부족해 보임
  - 점원을 통해 비말접촉 감염이 일어나면 당위성이 더 생기겠지만 아직 큰 이슈가 아님
### 넓은 범위의 언택트 드라이브 스루 모델
- 대형마트, 카페, 패스트 푸드, 고속도로 등과 같이 드라이브 스루 모델을 적용할 수 있는 분야를 문서적으로 어필
- 장점 : 개발 구현 난이도(우리가 기존하던 것에서 크게 추가할 필요는 없음)가 상승하지 않음
  - 단 오히려 하다보면 높아질 수 있음: `저쪽 산업에 적용할려면 이게 나을거 같은데? 하면서`
- 장점 : 논문을 통해 당위성 보충 가능
- 단점 : 대형마트, 카페, 패스트 푸드 등은 이미 유명한 드라이브 스루 모델이기 때문에 새로 적용될 수 있는 분야를 더 찾아야 함
  - 물론 우리가 제공하는 모델은 언택트 모델이기 때문에 다르다고 어필할 수 있지만, 다른 산업 분야를 더 제공해야만 어필할 수 있는 점이 강해진다고 보임

**Comment by kiJiyeon** [comment]
# 마트 픽업 서비스의 시작

2010년 7월5일부터 2013년 상반기까지 서울과 수도권 20여 개 점포에서 이마트 이마트몰에서 주문한 제품을 가까운 이마트 매장에서 찾을 수 있는'드라이브-스루 픽업' 서비스를 운영 하였다. [1].
하지만 저조한 이용률로 인해 2년만에 서비스를 중단했다.[2] 
이마트 관계자는 "이마트몰에서 2시간 단위로 예약배송 서비스를 운영하고 있기 때문에 드라이브 스루 서비스가 불필요하다고 판단했다"며 "배송서비스 운영하고 있는데 굳이 고객이 매장에 들러서 물건을 찾아갈 필요가 없다" 라고 이유를 밝혔다.

그 후, 2015년 9월 롯데마트는 서울 노원구 중계점에 모바일 앱(App)이나 PC로 상품을 주문 후 픽업 가능한 날짜와 시간을 선택해 상품을 수령할 수 있는 '드라이브 앤 픽 서비스' 운영을 시작했다. 하지만 저조한 이용률로 인해 서비스가 중단 되었다.

# 월마트의 전략을 따른 이마트의 픽업 서비스 [2,3]

월마트의 전략은 오프라인과 온라인을 연결하는 것이었다. 월마트의 클릭 앤 컬렉트(Click & Collect)는 소비자가 온라인에서 주문을 한 후 오프라인 매장에서 주문상품을 찾아가는 서비스이다. 매장에 직접 들어가지 않고 드라이브 스루 방식으로 픽업 센터에서 제품만 가져가는 방식이다. 월마트의 이런 전략이 성공할 수 있었던 배경에는 꾸준히 전자상거래 업체들을 인수한 것도 있지만, 무엇보다 있는 것을 잘 활용했다는 점이 주효했다. 압도적인 오프라인 인프라를 적극 활용한 것이다. 

위와 같은 월마트의 성공 전략을 따라서 SSG 닷컴에서는 2020년 12월 23일 부터 온라인에서 주문하고 집 근처 이마트에서 상품을 찾아갈 수 있는 '클릭 앤 콜렉트(Click & Collect)' 형태의 비대면 픽업 서비스를 시범 운영하였다. 클릭 앤 콜렉트는 미국 월마트 재도약의 핵심 서비스 중 하나다.

SSG닷컴은 이마트 성수점과 서수원점 두 곳에서 고객이 온라인으로 주문 후 해당 점포의 지정된 장소에서 상품을 찾아가는 '매장픽업 서비스'를 신설하고 지난 23일부터 베타테스트를 시작했다고 27일 밝혔다.

SSG닷컴에 입력된 주소지가 이마트 성수점과 서수원점 부근일 경우 '쓱배송' 상품에 한해 매장픽업 선택이 가능하고, 당일 주문해 당일 픽업으로만 이용 가능하다. 매일 자정부터 오후 4시까지 주문이 가능(점포 휴무일 제외)하며, 정오부터 오후 8시 사이에 이마트 고객주차장 내 지정된 픽업장소를 방문해 상품을 찾아갈 수 있다.

하지만 저조한 이용률로 인해 2021년 2월, 두달만에 서비스를 종료하였다. 
배송 물량 급증으로 배송이 밀려 잠시 이용률이 증가하는 듯 보였으나, 안정화 되면서 픽업 서비스 이용률이 감소하였기 때문이다.

# 결론

2010년 중반부터 시행된 마트 픽업 서비스가 당시에도 '온라인쇼핑+배송 서비스' 이용률에 뒤쳐져서 운영이 중단되었는데, 2021년 현재에도 저조한 이용률 때문에 마트 픽업 서비스 운영이 중단되는걸 보니까 대형마트에서 드라이브-스루 픽업 서비스 운영은 힘들지 않을까 하는 생각이듬!
(오히려 배송서비스가 너무너무 잘 되어있어서)




## References
[1][[포토뉴스]이마트몰 상품 픽업서비스](http://m.biz.khan.co.kr/view.html?art_id=201007051803565&code=920401#c2b)

[2][SSG닷컴- 이마트 '매장 픽업'서비스 두 달만에 중단](https://www.etnews.com/20210202000142)

[3][월마트 배우기 계속된다…SSG닷컴 주문 후 이마트서 비대면 수령](https://www.ajunews.com/view/20201227144603952)

**Comment by fora22** [comment]
@kiJiyeon @dkfma4915 우리 종합은 누가 하는 거였지?? 아름이였나??

**Comment by dkfma4915** [comment]
> @kiJiyeon @dkfma4915 우리 종합은 누가 하는 거였지?? 아름이였나??

안정하지않았어??! 사다리 타기 하기로했었음!

**Comment by fora22** [comment]
> 안정하지않았어??! 사다리 타기 하기로했었음!

어차피 아름이가 걸릴텐데 멋있게 아름이가 하는건 어떻게 생각함?

**Comment by dkfma4915** [comment]
# 유통 업계의 드라이브 스루
- 이미 백화점, 대형마트, 편의점 등 다양한 곳에서 드라이브 스루 서비스가 시작됨
- 방식 : **기존의 드라이브 스루 방식**과 동일
- 장점 : 배송비 부담X, 원하는 물품 소량 구매 가능, 시간 절약
- 단점 : 교통 혼잡↑, 문 앞 배송 더 선호, 이마트의 경우 예약 배송 서비스를 운영중이므로 이용률↓
- 공통점 : **판매자와 소비자 간 비말접촉에 대한 문제점 인식 및 해결점 X**
- 단점으로 인해 식료품 **매장픽업 서비스 이용률 저조**
- **패션 잡화 픽업 서비스**는 급증

# 의견
## 아름
### 고속도로 휴게소 음식 및 농특산물 판매 드라이브 스루 모델
- 스타벅스 DT 입지 관련 특징와 정부가 추진한 농산물 드라이브 스루를 결합한 아이디어
- 휴게소 음식뿐만 아니라 휴게소 지역 특산물을 판매
- 휴게소 특징을 이용 (교통량이 활발, 고속도로 IC 주변)
- 최근 휴게소 매출액 46.6% 감소 참고 기사 -> 신선한 농특산물 판매로 매출액 증가의 기회를 얻을 수 있지 않을까..?
## 대원
### 고속도로 휴게소 드라이브 스루
- 통행차량의 방문이 용이한 점을 이용하여 휴게소에서 비대면 서비스를 제공
- 비대면 플랫폼 제안 내용
  1. 홈페이지를 통해 고속도로 선택
  2. 고속도로 휴게소 선택
  3. 물품 선택
  4. 개발 내용대로 픽업
## 지연
- 중단된 사례가 있으므로 대형마트에서 드라이브 스루 픽업 서비스 운영은 힘들 것 같다는 의견
- 오히려 배송서비스가 너무 잘되어 있음

# 추가 논의
## 드라이브 스루 모델에 관한 당위성으로 추가
### 우리가 왜 드라이브 스루 모델을 개발하는지에 대해
- 코로나19로 인해 관광산업이 경제적으로 힘들어짐
- 다른 산업은 재택근무가 가능하지만 관광산업은 불가능
- 즉, 위기 상황(감염병 등)에 대응하여 관광 산업 관련 메뉴얼, 혁신적인 관광정책이 필요하다고 촉구
- **코로나19 대응 관광정책 = 드라이브 스루 관광 모델을 개발해야 한다**
## 대원's 사견
- [여기](https://github.com/JEoN-Ha/Senior-Project/issues/94#issuecomment-791930381)에 자세히 설명되어 있으므로 읽고 이야기 나누기!
