### ISSUE TITLE
Front 코드 수정을 위한 ID,PW 공유

### ISSUE THREAD

**Issue by dkfma4915** [JEoN-Ha/Senior-Project#95]
어제 오프라인 미팅때 말했던 ID, PW 공유 부탁합니다!!
그리고 DB 열고 닫고 할 때 어떻게 하는지 순서 간략하게 다시 정리해줄 수 있어?!
ID,PW는 카톡으로 보내줘~~

**Comment by fora22** [comment]
카톡으로 일단 설명 드렸지만, 일단 남깁니다!

DB 설정은 [여기](https://github.com/JEoN-Ha/Senior-Project/wiki/%5BWeb-for-Untact-DriveThru%5D-Express%EC%99%80-Rest-Api%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-%EB%9D%BC%EC%9A%B0%ED%8C%85%ED%95%98%EA%B8%B0)서 참고 바람!
