### ISSUE TITLE
Cors에러 해결방법에 대한 질문이있습니다!

### ISSUE THREAD

**Issue by kiJiyeon** [JEoN-Ha/Senior-Project#96]
몇주째 cors에러를 해결을 못하고있습니다ㅜㅜㅜ 
에러 메세지를 그대로 복사해서 검색해보고 cors에러 해결방법을 검색해봐도 해결이 안되는데 뭐가 문제인건지도 잘 모르겠습니다!! 
혹시 어떻게 해결 해야할 지 알려주실 수 있나요...?

![image](https://user-images.githubusercontent.com/48858836/110783476-d89b3180-82ab-11eb-8100-ce9d723b32b2.png)

**Comment by jongfeel** [comment]
websocket이군요.

front에 websocket 사용하는 코드군요.

요기 참고해 보시고, 문제가 해결 안되면 코드쪽 리뷰를 해보면 될 거 같습니다.
http://guswnsxodlf.github.io/enable-CORS-on-express

**Comment by kiJiyeon** [comment]
> websocket이군요.
> 
> 요기 참고해 보시고, 문제가 해결 안되면 코드쪽 리뷰를 해보면 될 거 같습니다.
> http://guswnsxodlf.github.io/enable-CORS-on-express

넵 확인해보겠습니다!
